export const EXCLUDE_SELECTORS = [
    '[class*="video"]',
    '[class*="player"]',
    '[id*="video"]',
    '[id*="player"]',
    '[class*="swiper"]',
    '[class*="carousel"]',
    '[class*="banner"]',
    '[class*="gallery"]',
    '[class*="douyin"]',
    '[class*="tiktok"]',
    '[class*="scroll"]',
    '[class*="scrollbar"]',
    '[class*="progress"]',
    '[class*="range"]',
    '[class*="volume"]',
  ];

export const CAPTCHA_SELECTORS = {
    slider: [
      '.captcha-slider',
      '.verify-slider',
      '#captcha-slider',
      '.slide-verify',
      '#nc_1_wrapper',
      '.nc-container',
      '.geetest_slider',
      '.geetest_holder',
      '.tcaptcha-transform',
      '.JDJRV-slide-inner',
      '.yidun_slider',
      '[class*="captcha"][class*="slider"]',
      '[class*="verify"][class*="slider"]',
      '[id*="captcha"][id*="slider"]',
      '[id*="verify"][id*="slider"]',
    ],

    image: [
      '[class*="captcha-image"]',
      '[id*="captcha-image"]',
      '.verify-img',
      '.captcha-img',
      'img[src*="captcha"]',
      'img[alt*=""]',
      'img[alt*="captcha"]',
    ],

    recaptcha: [
      'iframe[src*="recaptcha"]',
      '.g-recaptcha',
      '#g-recaptcha',
      '[class*="recaptcha"]',
      'iframe[title*="reCAPTCHA"]',
    ],

    hcaptcha: [
      'iframe[src*="hcaptcha"]',
      '.h-captcha',
      '#h-captcha',
      '[class*="hcaptcha"]',
      'iframe[title*="hCaptcha"]',
    ],

    cloudflare: [
      '#challenge-form',
      '.cf-challenge',
      '[id*="cf-challenge"]',
      'iframe[src*="challenges.cloudflare.com"]',
      '#cf-wrapper',
      '.ray-id',
    ],

    generic: [
      '[class*="captcha"]',
      '[id*="captcha"]',
      '[class*="verify"]',
      '[id*="verify"]',
      '[class*="challenge"]',
      '[id*="challenge"]',
      'iframe[src*="captcha"]',
      'iframe[src*="verify"]',
    ],
  };

export const CAPTCHA_KEYWORDS = {
    title: [
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      'captcha',
      'challenge',
      'verify',
      'verification',
      'robot',
      'human',
      'security check',
      'bot check',
      'anti-bot',
      'cloudflare',
      'geetest',
      'recaptcha',
      'hcaptcha',
      'turnstile',
    ],
    url: [
      'captcha',
      'challenge',
      'verify',
      'verification',
      'robot-check',
      'security-check',
      'bot-check',
      'cdn-cgi/challenge',
      'cloudflare',
      'akamai',
      'geetest',
      'recaptcha',
      'hcaptcha',
      'turnstile',
      'datadome',
      'perimeter',
      'px-captcha',
    ],
    text: [
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      '',
      'Please verify',
      'Verify you are human',
      'Complete the security check',
      'Slide to verify',
      'Click to verify',
      'Drag the slider',
      'Prove you are human',
      'I am not a robot',
      'Checking your browser',
      'Just a moment',
      'Checking if the site connection is secure',
      'This process is automatic',
      'Protected by',
      'Powered by',
    ],
  };

export const EXCLUDE_KEYWORDS = {
    title: ['', '', '', '', '', '', '', 'verification code', 'enter code', 'sms code'],
    url: [
      'verify-email',
      'verify-phone',
      'email-verification',
      'account-verification',
      'verify-account',
    ],
    text: ['', '', '', '', '', 'Enter verification code', 'Get code', 'Send code'],
  };

