export {
  CAPTCHA_KEYWORDS,
  CAPTCHA_MATCH_RULES,
  DOM_MATCH_RULES,
  EXCLUDE_KEYWORDS,
  EXCLUDE_MATCH_RULES,
  FALLBACK_CAPTCHA_KEYWORDS,
  FALLBACK_EXCLUDE_KEYWORDS,
  CAPTCHA_SELECTORS,
  EXCLUDE_SELECTORS,
} from '@modules/captcha/rules';
