import { resolve } from 'node:path';
import type { Phase } from '@tests/e2e/helpers/types';

const WASM_FIXTURE_PATH = resolve(process.cwd(), 'tests', 'e2e', 'fixtures', 'wasm', 'sample.wasm');

export const systemPhases: Phase[] = [
  {
    name: 'Antidebug',
    setup: [],
    tools: [
      'antidebug_detect_protections',
      'antidebug_bypass_all',
      'antidebug_bypass_debugger_statement',
      'antidebug_bypass_console_detect',
      'antidebug_bypass_stack_trace',
      'antidebug_bypass_timing',
    ],
  },
  {
    name: 'Sourcemap',
    concurrent: true,
    setup: [],
    tools: [
      'sourcemap_discover',
      'source_map_extract',
      'sourcemap_fetch_and_parse',
      'sourcemap_reconstruct_tree',
    ],
  },
  {
    name: 'Workflow',
    setup: [],
    tools: [
      'page_script_register',
      'page_script_run',
      'js_bundle_search',
      'webpack_enumerate',
      'web_api_capture_session',
      'api_probe_batch',
      'tab_workflow',
      'script_replace_persist',
    ],
  },
  {
    name: 'Process',
    group: 'compute-system',
    setup: async (call) => {
      // Find chrome/browser processes to get a real PID for process/memory tools
      await call('process_find', { pattern: 'chrome' });
      await new Promise((r) => setTimeout(r, 50));
    },
    tools: [
      'process_list',
      'process_get',
      'process_windows',
      'process_find',
      'process_find_chromium',
      'process_check_debug_port',
      'process_launch_debug',
    ],
  },
  {
    name: 'Module Enumeration',
    concurrent: true,
    group: 'compute-system',
    setup: [],
    tools: ['check_debug_port', 'enumerate_modules'],
  },
  {
    name: 'Memory (read-only)',
    concurrent: true,
    group: 'compute-system',
    setup: [],
    tools: [
      'memory_list_regions',
      'memory_dump_region',
      'memory_read',
      'memory_scan',
      'memory_scan_filtered',
      'memory_check_protection',
      'memory_audit_export',
    ],
  },
  {
    name: 'Memory (write)',
    concurrent: true,
    group: 'compute-system',
    setup: [],
    tools: ['memory_write', 'memory_batch_write'],
  },
  {
    name: 'WASM',
    concurrent: true,
    group: 'compute-core',
    setup: async (call) => {
      // Use local WASM fixture for deterministic testing
      await call(
        'wasm_inspect_sections',
        { inputPath: WASM_FIXTURE_PATH, sections: 'headers' },
        15_000,
      );
    },
    tools: [
      'wasm_dump',
      'wasm_inspect_sections',
      'wasm_decompile',
      'wasm_disassemble',
      'wasm_optimize',
      'wasm_memory_inspect',
      'wasm_vmp_trace',
      'wasm_offline_run',
    ],
  },
  {
    name: 'Platform',
    concurrent: true,
    group: 'compute-core',
    setup: [],
    tools: [
      'asar_extract',
      'asar_search',
      'electron_attach',
      'electron_inspect_app',
      'electron_scan_userdata',
      'electron_check_fuses',
      'electron_patch_fuses',
      'electron_launch_debug',
      'electron_debug_status',
      'electron_ipc_sniff',
    ],
  },
  {
    name: 'Miniapp',
    concurrent: true,
    group: 'compute-core',
    setup: [],
    tools: ['miniapp_pkg_scan', 'miniapp_pkg_unpack', 'miniapp_pkg_analyze'],
  },
  {
    name: 'Injection',
    concurrent: true,
    group: 'compute-system',
    setup: [],
    tools: ['inject_dll', 'inject_shellcode'],
  },
  {
    name: 'External Bridges',
    concurrent: true,
    group: 'compute-core',
    setup: [],
    tools: ['frida_bridge', 'jadx_bridge'],
  },
  {
    name: 'Trace & Time-Travel',
    group: 'compute-core',
    setup: [],
    tools: [
      'start_trace_recording',
      'stop_trace_recording',
      'query_trace_sql',
      'seek_to_timestamp',
      'diff_heap_snapshots',
      'export_trace',
      'summarize_trace',
    ],
  },
  {
    name: 'Sandbox Execution',
    group: 'compute-core',
    setup: [],
    tools: ['execute_sandbox_script'],
  },
  {
    name: 'Macro Orchestration',
    group: 'compute-core',
    setup: [],
    tools: ['run_macro', 'list_macros'],
  },
  {
    name: 'Search & Routing',
    concurrent: true,
    group: 'compute-core',
    setup: [],
    tools: ['search_tools', 'route_tool', 'describe_tool'],
  },
  {
    name: 'Cross-Domain Analysis',
    concurrent: true,
    group: 'compute-browser',
    setup: [],
    tools: [
      'cross_domain_capabilities',
      'cross_domain_suggest_workflow',
      'cross_domain_health',
      'cross_domain_correlate_all',
      'cross_domain_evidence_export',
      'cross_domain_evidence_stats',
    ],
  },
  {
    name: 'Evidence',
    concurrent: true,
    group: 'compute-browser',
    setup: [],
    tools: [
      'evidence_query_url',
      'evidence_query_function',
      'evidence_query_script',
      'evidence_export_json',
      'evidence_export_markdown',
      'evidence_chain',
    ],
  },
  {
    name: 'State Board',
    group: 'compute-core',
    setup: [],
    tools: [
      'state_board_set',
      'state_board_get',
      'state_board_delete',
      'state_board_list',
      'state_board_watch',
      'state_board_unwatch',
      'state_board_history',
      'state_board_export',
      'state_board_import',
      'state_board_clear',
    ],
  },
  {
    name: 'TLS & Crypto',
    concurrent: true,
    group: 'compute-core',
    setup: [],
    tools: [
      'tls_keylog_enable',
      'tls_keylog_parse',
      'tls_keylog_disable',
      'tls_decrypt_payload',
      'tls_keylog_summarize',
      'tls_keylog_lookup_secret',
      'tls_cert_pin_bypass',
      'tls_handshake_parse',
      'tls_parse_handshake',
      'tls_cipher_suites',
      'tls_parse_certificate',
      'tls_cert_pin_bypass_frida',
    ],
  },
  {
    name: 'Network Raw',
    concurrent: true,
    group: 'compute-core',
    setup: [],
    tools: [
      'net_raw_tcp_send',
      'net_raw_tcp_listen',
      'net_raw_udp_send',
      'net_raw_udp_listen',
      'net_raw_tcp_scan',
    ],
  },
  {
    name: 'Instrumentation Sessions',
    group: 'compute-core',
    setup: [],
    tools: [
      'instrumentation_session_create',
      'instrumentation_session_list',
      'instrumentation_session_destroy',
      'instrumentation_session_status',
      'instrumentation_operation_register',
      'instrumentation_operation_list',
      'instrumentation_artifact_record',
      'instrumentation_artifact_query',
      'instrumentation_hook_preset',
      'instrumentation_network_replay',
    ],
  },
  {
    name: 'Memory Scanning (cheat-engine style)',
    concurrent: true,
    group: 'compute-system',
    setup: [],
    tools: [
      'memory_first_scan',
      'memory_next_scan',
      'memory_unknown_scan',
      'memory_pointer_scan',
      'memory_group_scan',
      'memory_scan_list',
      'memory_scan_delete',
      'memory_scan_export',
    ],
  },
  {
    name: 'Memory Pointer Chains',
    concurrent: true,
    group: 'compute-system',
    setup: [],
    tools: [
      'memory_pointer_chain_scan',
      'memory_pointer_chain_validate',
      'memory_pointer_chain_resolve',
      'memory_pointer_chain_export',
    ],
  },
  {
    name: 'Memory Structure Analysis',
    concurrent: true,
    group: 'compute-system',
    setup: [],
    tools: [
      'memory_structure_analyze',
      'memory_vtable_parse',
      'memory_structure_export_c',
      'memory_structure_compare',
    ],
  },
  {
    name: 'Memory Patching',
    concurrent: true,
    group: 'compute-system',
    setup: [],
    tools: [
      'memory_patch_bytes',
      'memory_patch_nop',
      'memory_patch_undo',
      'memory_code_caves',
      'memory_write_value',
      'memory_freeze',
      'memory_unfreeze',
      'memory_dump',
      'memory_write_undo',
      'memory_write_redo',
    ],
  },
  {
    name: 'Protocol Inference',
    concurrent: true,
    group: 'compute-core',
    setup: [],
    tools: [
      'proto_define_pattern',
      'proto_auto_detect',
      'proto_infer_fields',
      'proto_infer_state_machine',
      'proto_export_schema',
      'proto_visualize_state',
    ],
  },
  {
    name: 'Mojo IPC',
    concurrent: true,
    group: 'compute-browser',
    setup: [],
    tools: [
      'mojo_monitor_start',
      'mojo_monitor_stop',
      'mojo_decode_message',
      'mojo_list_interfaces',
      'mojo_messages_get',
    ],
  },
  {
    name: 'V8 Inspector',
    concurrent: true,
    group: 'compute-browser',
    setup: async (call) => {
      await call('page_navigate', {
        url: 'data:text/html,<html><body><h1>jshook e2e</h1><script>window.__e2e=true;</script></body></html>',
        waitUntil: 'load',
        timeout: 15000,
      });
      await call(
        'page_evaluate',
        {
          code: `(() => {
            globalThis.__jshookV8E2E = {
              tag: 'v8-e2e-node',
              createdAt: Date.now(),
              nested: { score: 42, active: true },
            };
            return true;
          })()`,
        },
        15000,
      );
      await call('v8_heap_snapshot_capture', {}, 60000);
      await new Promise((r) => setTimeout(r, 100));
      await call('v8_heap_snapshot_capture', {}, 60000);
    },
    tools: [
      'v8_heap_snapshot_capture',
      'v8_heap_snapshot_analyze',
      'v8_heap_diff',
      'v8_object_inspect',
      'v8_heap_stats',
      'v8_bytecode_extract',
      'v8_bytecode_decompile',
      'v8_version_detect',
      'v8_jit_inspect',
    ],
  },
  {
    name: 'Skia Canvas',
    concurrent: true,
    group: 'compute-browser',
    setup: [],
    tools: [
      'skia_detect_renderer',
      'skia_extract_scene',
      'skia_correlate_objects',
      'canvas_engine_fingerprint',
      'canvas_scene_dump',
      'canvas_pick_object_at_point',
    ],
  },
  {
    name: 'Syscall Monitor',
    concurrent: true,
    group: 'compute-browser',
    setup: [],
    tools: [
      'syscall_start_monitor',
      'syscall_stop_monitor',
      'syscall_capture_events',
      'syscall_correlate_js',
      'syscall_filter',
      'syscall_get_stats',
    ],
  },
  {
    name: 'Webhook',
    concurrent: true,
    group: 'compute-core',
    setup: [],
    tools: ['webhook_create', 'webhook_list', 'webhook_delete', 'webhook_commands'],
  },
  {
    name: 'Stealth Advanced',
    concurrent: true,
    group: 'compute-browser',
    setup: [],
    tools: ['stealth_configure_jitter', 'stealth_generate_fingerprint', 'stealth_verify'],
  },
  {
    name: 'Extension Workflows',
    concurrent: true,
    group: 'compute-browser',
    setup: ['reload_extensions', 'list_extension_workflows'],
    tools: [
      'install_extension',
      'extension_reload',
      'extension_uninstall',
      'extension_execute_in_context',
      'batch_register',
      'list_extension_workflows',
      'run_extension_workflow',
      'register_account_flow',
    ],
  },
  {
    name: 'Process Kill (last)',
    group: 'cleanup',
    setup: [],
    tools: ['process_kill'],
  },
];
