import { resolve } from 'node:path';
import type { Phase } from '@tests/e2e/helpers/types';

const WASM_FIXTURE_PATH = resolve(process.cwd(), 'tests', 'e2e', 'fixtures', 'wasm', 'sample.wasm');

export const systemPhases: Phase[] = [
  {
    name: 'Antidebug',
    setup: [],
    tools: ['antidebug_detect_protections', 'antidebug_bypass'],
  },
  {
    name: 'Sourcemap',
    concurrent: true,
    setup: [],
    tools: [
      'sourcemap_discover',
      'sourcemap_fetch_and_parse',
      'sourcemap_reconstruct_tree',
      'sourcemap_parse_v4',
    ],
  },
  {
    name: 'Workflow',
    setup: [],
    tools: [
      'page_script_register',
      'page_script_run',
      'js_bundle_search',
      'webpack_enumerate',
      'api_probe_batch',
      'tab_workflow',
      'script_replace_persist',
    ],
  },
  {
    name: 'Process',
    group: 'compute-system',
    setup: [],
    tools: ['process_windows', 'process_check_debug_port', 'process_launch_debug'],
  },
  {
    name: 'Module Enumeration',
    concurrent: true,
    group: 'compute-system',
    setup: [],
    tools: ['check_debug_port', 'enumerate_modules'],
  },
  {
    name: 'Memory (read-only)',
    concurrent: true,
    group: 'compute-system',
    setup: [],
    tools: [
      'memory_list_regions',
      'memory_dump_region',
      'memory_read',
      'memory_scan',
      'memory_scan_filtered',
      'memory_check_protection',
      'memory_audit_export',
    ],
  },
  {
    name: 'Memory (write)',
    concurrent: true,
    group: 'compute-system',
    setup: [],
    tools: ['memory_write', 'memory_batch_write'],
  },
  {
    name: 'WASM',
    concurrent: true,
    group: 'compute-core',
    setup: async (call) => {
      // Use local WASM fixture for deterministic testing
      await call(
        'wasm_inspect_sections',
        { inputPath: WASM_FIXTURE_PATH, sections: 'headers' },
        15_000,
      );
    },
    tools: [
      'wasm_dump',
      'wasm_inspect_sections',
      'wasm_decompile',
      'wasm_disassemble',
      'wasm_optimize',
      'wasm_memory_inspect',
      'wasm_vmp_trace',
      'wasm_offline_run',
      'wasm_to_c',
      'wasm_detect_obfuscation',
      'wasm_instrument_trace',
    ],
  },
  {
    name: 'Protocol Fingerprinting',
    concurrent: true,
    group: 'compute-core',
    setup: [],
    tools: ['proto_fingerprint'],
  },
  {
    name: 'Syscall Hook',
    concurrent: true,
    group: 'compute-core',
    setup: [],
    tools: ['syscall_ebpf_trace'],
  },
  {
    name: 'Platform',
    concurrent: true,
    group: 'compute-core',
    setup: [],
    tools: [
      'asar_extract',
      'asar_search',
      'electron_attach',
      'electron_inspect_app',
      'electron_scan_userdata',
      'electron_check_fuses',
      'electron_patch_fuses',
      'electron_launch_debug',
      'electron_debug_status',
      'electron_ipc_sniff',
    ],
  },
  {
    name: 'Miniapp',
    concurrent: true,
    group: 'compute-core',
    setup: [],
    tools: ['miniapp_pkg_scan', 'miniapp_pkg_unpack', 'miniapp_pkg_analyze'],
  },
  {
    name: 'Injection',
    concurrent: true,
    group: 'compute-system',
    setup: [],
    tools: ['inject_dll', 'inject_shellcode'],
  },
  {
    name: 'External Bridges',
    concurrent: true,
    group: 'compute-core',
    setup: [],
    tools: ['frida_attach', 'jadx_decompile'],
  },
  {
    name: 'Trace & Time-Travel',
    group: 'compute-core',
    setup: [],
    tools: [
      'start_trace_recording',
      'stop_trace_recording',
      'query_trace_sql',
      'seek_to_timestamp',
      'diff_heap_snapshots',
      'export_trace',
      'summarize_trace',
    ],
  },
  {
    name: 'Sandbox Execution',
    group: 'compute-core',
    setup: [],
    tools: ['execute_sandbox_script'],
  },
  {
    name: 'Macro Orchestration',
    group: 'compute-core',
    setup: [],
    tools: ['run_macro', 'list_macros'],
  },
  {
    name: 'Search & Routing',
    concurrent: true,
    group: 'compute-core',
    setup: [],
    tools: ['search_tools', 'route_tool', 'describe_tool'],
  },
  {
    name: 'Cross-Domain Analysis',
    concurrent: true,
    group: 'compute-browser',
    setup: [],
    tools: [
      'cross_domain_capabilities',
      'cross_domain_suggest_workflow',
      'cross_domain_health',
      'cross_domain_correlate_all',
      'cross_domain_evidence_export',
      'cross_domain_evidence_stats',
    ],
  },
  {
    name: 'Evidence',
    concurrent: true,
    group: 'compute-browser',
    setup: [],
    tools: ['evidence_query', 'evidence_export', 'evidence_chain'],
  },
  {
    name: 'State Board',
    group: 'compute-core',
    setup: [],
    tools: ['state_board', 'state_board_watch', 'state_board_io'],
  },
  {
    name: 'TLS & Crypto',
    concurrent: true,
    group: 'compute-core',
    setup: [],
    tools: [
      'tls_keylog_enable',
      'tls_keylog_parse',
      'tls_keylog_disable',
      'tls_decrypt_payload',
      'tls_keylog_summarize',
      'tls_keylog_lookup_secret',
      'tls_cert_pin_bypass',
      'tls_parse_handshake',
      'tls_cipher_suites',
      'tls_parse_certificate',
      'tls_cert_pin_bypass_frida',
    ],
  },
  {
    name: 'Network Raw',
    concurrent: true,
    group: 'compute-core',
    setup: [],
    tools: [
      'net_raw_tcp_send',
      'net_raw_tcp_listen',
      'net_raw_udp_send',
      'net_raw_udp_listen',
      'net_raw_tcp_scan',
    ],
  },
  {
    name: 'Instrumentation Sessions',
    group: 'compute-core',
    setup: [],
    tools: [
      'instrumentation_session',
      'instrumentation_operation',
      'instrumentation_artifact',
      'instrumentation_hook_preset',
      'instrumentation_network_replay',
    ],
  },
  {
    name: 'Memory Scanning (cheat-engine style)',
    concurrent: true,
    group: 'compute-system',
    setup: [],
    tools: [
      'memory_first_scan',
      'memory_next_scan',
      'memory_unknown_scan',
      'memory_pointer_scan',
      'memory_group_scan',
      { tool: 'memory_scan_session', name: 'memory_scan_list', argsKey: 'memory_scan_list' },
      { tool: 'memory_scan_session', name: 'memory_scan_delete', argsKey: 'memory_scan_delete' },
      { tool: 'memory_scan_session', name: 'memory_scan_export', argsKey: 'memory_scan_export' },
    ],
  },
  {
    name: 'Memory Pointer Chains',
    concurrent: true,
    group: 'compute-system',
    setup: [],
    tools: [
      {
        tool: 'memory_pointer_chain',
        name: 'memory_pointer_chain_scan',
        argsKey: 'memory_pointer_chain_scan',
      },
      {
        tool: 'memory_pointer_chain',
        name: 'memory_pointer_chain_validate',
        argsKey: 'memory_pointer_chain_validate',
      },
      {
        tool: 'memory_pointer_chain',
        name: 'memory_pointer_chain_resolve',
        argsKey: 'memory_pointer_chain_resolve',
      },
      {
        tool: 'memory_pointer_chain',
        name: 'memory_pointer_chain_export',
        argsKey: 'memory_pointer_chain_export',
      },
    ],
  },
  {
    name: 'Memory Structure Analysis',
    concurrent: true,
    group: 'compute-system',
    setup: [],
    tools: [
      'memory_structure_analyze',
      'memory_vtable_parse',
      'memory_structure_export_c',
      'memory_structure_compare',
    ],
  },
  {
    name: 'Memory Patching',
    concurrent: true,
    group: 'compute-system',
    setup: [],
    tools: [
      'memory_patch_bytes',
      'memory_patch_nop',
      'memory_patch_undo',
      'memory_code_caves',
      'memory_write_value',
      'memory_freeze',
      { tool: 'memory_freeze', name: 'memory_unfreeze', argsKey: 'memory_unfreeze' },
      'memory_dump',
      { tool: 'memory_write_history', name: 'memory_write_undo', argsKey: 'memory_write_undo' },
      { tool: 'memory_write_history', name: 'memory_write_redo', argsKey: 'memory_write_redo' },
    ],
  },
  {
    name: 'Protocol Inference',
    concurrent: true,
    group: 'compute-core',
    setup: [],
    tools: [
      'proto_define_pattern',
      'proto_auto_detect',
      'proto_infer_fields',
      'proto_infer_state_machine',
      'proto_export_schema',
      'proto_visualize_state',
    ],
  },
  {
    name: 'Mojo IPC',
    concurrent: true,
    group: 'compute-browser',
    setup: [],
    tools: ['mojo_monitor', 'mojo_decode_message', 'mojo_list_interfaces', 'mojo_messages_get'],
  },
  {
    name: 'V8 Inspector',
    concurrent: true,
    group: 'compute-browser',
    setup: async (call) => {
      await call('page_navigate', {
        url: 'data:text/html,<html><body><h1>jshook e2e</h1><script>window.__e2e=true;</script></body></html>',
        waitUntil: 'load',
        timeout: 15000,
      });
      await call(
        'page_evaluate',
        {
          code: `(() => {
            globalThis.__jshookV8E2E = {
              tag: 'v8-e2e-node',
              createdAt: Date.now(),
              nested: { score: 42, active: true },
            };
            return true;
          })()`,
        },
        15000,
      );
      await call('v8_heap_snapshot_capture', {}, 60000);
      await new Promise((r) => setTimeout(r, 100));
      await call('v8_heap_snapshot_capture', {}, 60000);
    },
    tools: [
      'v8_heap_snapshot_capture',
      'v8_heap_snapshot_analyze',
      'v8_heap_diff',
      'v8_object_inspect',
      'v8_heap_stats',
      'v8_bytecode_extract',
      'v8_bytecode_decompile',
      'v8_version_detect',
      'v8_jit_inspect',
    ],
  },
  {
    name: 'Skia Canvas',
    concurrent: true,
    group: 'compute-browser',
    setup: [],
    tools: [
      'skia_detect_renderer',
      'skia_extract_scene',
      'skia_correlate_objects',
      'canvas_engine_fingerprint',
      'canvas_scene_dump',
      'canvas_pick_object_at_point',
    ],
  },
  {
    name: 'Syscall Monitor',
    concurrent: true,
    group: 'compute-browser',
    setup: [],
    tools: [
      'syscall_start_monitor',
      'syscall_stop_monitor',
      'syscall_capture_events',
      'syscall_correlate_js',
      'syscall_filter',
      'syscall_get_stats',
    ],
  },
  {
    name: 'Webhook',
    concurrent: true,
    group: 'compute-core',
    setup: [],
    tools: ['webhook'],
  },
  {
    name: 'Stealth Advanced',
    concurrent: true,
    group: 'compute-browser',
    setup: [],
    tools: ['stealth_configure_jitter', 'stealth_generate_fingerprint', 'stealth_verify'],
  },
  {
    name: 'Extension Workflows',
    concurrent: true,
    group: 'compute-browser',
    setup: ['reload_extensions', 'list_extension_workflows'],
    tools: [
      'extension_reload',
      'extension_uninstall',
      'extension_execute_in_context',
      'batch_register',
      'list_extension_workflows',
      'run_extension_workflow',
    ],
  },
  {
    name: 'Memory Advanced',
    concurrent: true,
    group: 'compute-system',
    setup: [],
    tools: [
      'memory_scan_session',
      'memory_pointer_chain',
      'memory_breakpoint',
      'memory_speedhack',
      'memory_write_history',
      'memory_heap_enumerate',
      'memory_heap_stats',
      'memory_heap_anomalies',
      'memory_pe_headers',
      'memory_pe_imports_exports',
      'memory_inline_hook_detect',
      'memory_anticheat_detect',
      'memory_guard_pages',
      'memory_integrity_check',
    ],
  },
  {
    name: 'Profiling (short-name aliases)',
    concurrent: true,
    group: 'compute-browser',
    setup: [],
    tools: ['performance_coverage', 'performance_trace', 'profiler_cpu', 'profiler_heap_sampling'],
  },
  {
    name: 'Network Tools (short-name aliases)',
    concurrent: true,
    group: 'compute-core',
    setup: [],
    tools: ['network_monitor', 'network_rtt_measure'],
  },
  {
    name: 'TCP/TLS Raw',
    concurrent: true,
    group: 'compute-core',
    setup: [],
    tools: [
      'tcp_open',
      'tcp_write',
      'tcp_read_until',
      'tcp_close',
      'tls_open',
      'tls_write',
      'tls_read_until',
      'tls_close',
      'tls_probe_endpoint',
      'websocket_open',
      'websocket_send_frame',
      'websocket_read_frame',
      'websocket_close',
    ],
  },
  {
    name: 'HTTP Builders',
    concurrent: true,
    group: 'compute-core',
    setup: [],
    tools: ['http_request_build', 'http_plain_request', 'http2_probe', 'http2_frame_build'],
  },
  {
    name: 'Packet & Payload Builders',
    concurrent: true,
    group: 'compute-core',
    setup: [],
    tools: [
      'payload_template_build',
      'payload_mutate',
      'ethernet_frame_build',
      'arp_build',
      'raw_ip_packet_build',
      'icmp_echo_build',
      'checksum_apply',
      'pcap_write',
      'pcap_read',
    ],
  },
  {
    name: 'Proxy Domain',
    concurrent: true,
    group: 'compute-core',
    setup: [],
    tools: [
      'proxy_start',
      'proxy_stop',
      'proxy_status',
      'proxy_export_ca',
      'proxy_add_rule',
      'proxy_get_requests',
      'proxy_clear_logs',
      'proxy_setup_adb_device',
    ],
  },
  {
    name: 'Mojo & Network Traceroute',
    concurrent: true,
    group: 'compute-core',
    setup: [],
    tools: ['mojo_monitor', 'network_traceroute', 'network_icmp_probe'],
  },
  {
    name: 'Evidence (short-name aliases)',
    concurrent: true,
    group: 'compute-browser',
    setup: [],
    tools: ['evidence_query', 'evidence_export'],
  },
  {
    name: 'Console (short-name aliases)',
    concurrent: true,
    group: 'compute-browser',
    setup: [],
    tools: ['console_inject', 'console_buffers'],
  },
  {
    name: 'Trace (short-name alias)',
    concurrent: true,
    group: 'compute-core',
    setup: [],
    tools: ['trace_recording'],
  },
  {
    name: 'Debugger (short-name aliases)',
    concurrent: true,
    group: 'compute-browser',
    setup: [],
    tools: ['breakpoint', 'watch'],
  },
  {
    name: 'Search Meta-Tools (short-name aliases)',
    concurrent: true,
    group: 'compute-core',
    setup: [],
    tools: ['activate_tools', 'deactivate_tools', 'activate_domain', 'call_tool'],
  },
  {
    name: 'WS Monitor (short-name alias)',
    concurrent: true,
    group: 'compute-browser',
    setup: [],
    tools: ['ws_monitor'],
  },
  {
    name: 'Extension Install',
    concurrent: true,
    group: 'compute-core',
    setup: [],
    tools: ['install_extension'],
  },
  {
    name: 'LLM Suggest',
    concurrent: true,
    group: 'compute-core',
    setup: [],
    tools: ['llm_suggest_names'],
  },
];
