import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { spawn } from 'node:child_process';
import { printNativeIgnitionBytecode } from '@modules/v8-inspector/NativeBytecodePrinter';

const STATUS_PREFIX = '__JSHOOK_BYTECODE_STATUS__:';
const TARGET_NAME = '__jshookBytecodeTarget__';

type EventHandler = (...args: any[]) => void;

function createFakeChildProcess() {
  const processHandlers = new Map<string, EventHandler[]>();
  const stdoutHandlers = new Map<string, EventHandler[]>();
  const stderrHandlers = new Map<string, EventHandler[]>();
  let stdinData = '';

  const child = {
    stdout: {
      setEncoding: vi.fn(),
      on: vi.fn((event: string, handler: EventHandler) => {
        const handlers = stdoutHandlers.get(event) ?? [];
        handlers.push(handler);
        stdoutHandlers.set(event, handlers);
      }),
    },
    stderr: {
      setEncoding: vi.fn(),
      on: vi.fn((event: string, handler: EventHandler) => {
        const handlers = stderrHandlers.get(event) ?? [];
        handlers.push(handler);
        stderrHandlers.set(event, handlers);
      }),
    },
    stdin: {
      end: vi.fn((chunk: string) => {
        stdinData = chunk;
      }),
    },
    kill: vi.fn(),
    on: vi.fn((event: string, handler: EventHandler) => {
      const handlers = processHandlers.get(event) ?? [];
      handlers.push(handler);
      processHandlers.set(event, handlers);
    }),
    emit(event: string, ...args: any[]) {
      for (const handler of processHandlers.get(event) ?? []) {
        handler(...args);
      }
    },
    emitStdout(chunk: string) {
      for (const handler of stdoutHandlers.get('data') ?? []) {
        handler(chunk);
      }
    },
    emitStderr(chunk: string) {
      for (const handler of stderrHandlers.get('data') ?? []) {
        handler(chunk);
      }
    },
    getStdinData() {
      return stdinData;
    },
  };

  return child;
}

vi.mock('node:child_process', () => ({
  spawn: vi.fn(),
}));

const mockSpawn = vi.mocked(spawn);

function emitAndClose(
  child: ReturnType<typeof createFakeChildProcess>,
  {
    code = 0,
    stdout = '',
    stderr = '',
    error,
  }: {
    code?: number;
    stdout?: string;
    stderr?: string;
    error?: Error;
  },
) {
  queueMicrotask(() => {
    if (stdout.length > 0) {
      child.emitStdout(stdout);
    }
    if (stderr.length > 0) {
      child.emitStderr(stderr);
    }
    if (error) {
      child.emit('error', error);
      return;
    }
    child.emit('close', code);
  });
}

describe('printNativeIgnitionBytecode', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  it('extracts bytecode on the requested function filter', async () => {
    const child = createFakeChildProcess();
    mockSpawn.mockImplementationOnce(() => {
      emitAndClose(child, {
        stdout: [
          '[generated bytecode for function: myFunc (0x123)]',
          'Bytecode length: 2',
          '0 @ LdaZero',
          '1 @ Return',
          `${STATUS_PREFIX}done`,
          '',
        ].join('\n'),
      });
      return child as any;
    });

    const result = await printNativeIgnitionBytecode(
      {
        functionName: 'myFunc',
        sourceSlice: 'function myFunc() { return 1; }',
      },
      100,
    );

    expect(result).toMatchObject({
      available: true,
      format: 'ignition-bytecode',
      functionName: 'myFunc',
      rawIgnitionBytecodeAvailable: true,
    });
    expect(result.bytecode).toContain('Bytecode length: 2');
    expect(mockSpawn).toHaveBeenCalledWith(
      process.execPath,
      ['--print-bytecode', '--print-bytecode-filter=myFunc', '-'],
      { stdio: ['pipe', 'pipe', 'pipe'] },
    );
    expect(child.getStdinData()).toContain(`${TARGET_NAME} = (function myFunc() { return 1; });`);
  });

  it('falls back to the placeholder filter for object member sources', async () => {
    const firstChild = createFakeChildProcess();
    const secondChild = createFakeChildProcess();

    mockSpawn
      .mockImplementationOnce(() => {
        emitAndClose(firstChild, {
          stdout: `${STATUS_PREFIX}done\n`,
        });
        return firstChild as any;
      })
      .mockImplementationOnce(() => {
        emitAndClose(secondChild, {
          stdout: [
            `[generated bytecode for function: ${TARGET_NAME} (0x999)]`,
            'Bytecode length: 1',
            '0 @ Return',
            `${STATUS_PREFIX}done`,
            '',
          ].join('\n'),
        });
        return secondChild as any;
      });

    const result = await printNativeIgnitionBytecode(
      {
        functionName: 'myMethod',
        sourceSlice: 'myMethod() { return 1; }',
      },
      100,
    );

    expect(mockSpawn).toHaveBeenCalledTimes(2);
    expect(result).toMatchObject({
      available: true,
      functionName: 'myMethod',
      rawIgnitionBytecodeAvailable: true,
    });
    expect(firstChild.getStdinData()).toContain(
      'const __jshookHolder = { myMethod() { return 1; } };',
    );
  });

  it('surfaces resolve failures from the isolated bootstrap', async () => {
    const firstChild = createFakeChildProcess();
    const secondChild = createFakeChildProcess();

    mockSpawn
      .mockImplementationOnce(() => {
        emitAndClose(firstChild, {
          code: 2,
          stdout: `${STATUS_PREFIX}resolve-failed\n`,
        });
        return firstChild as any;
      })
      .mockImplementationOnce(() => {
        emitAndClose(secondChild, {
          code: 2,
          stdout: `${STATUS_PREFIX}resolve-failed\n`,
        });
        return secondChild as any;
      });

    const result = await printNativeIgnitionBytecode(
      {
        functionName: 'myFunc',
        sourceSlice: 'not valid javascript',
      },
      100,
    );

    expect(result).toMatchObject({
      available: false,
      functionName: 'myFunc',
      rawIgnitionBytecodeAvailable: false,
    });
    expect(result.reason).toContain('Unable to reconstruct an executable function');
  });

  it('reports isolated invocation errors from the status stream', async () => {
    const firstChild = createFakeChildProcess();
    const secondChild = createFakeChildProcess();

    mockSpawn
      .mockImplementationOnce(() => {
        emitAndClose(firstChild, {
          code: 9,
          stdout: `${STATUS_PREFIX}invoke-error:ReferenceError: document is not defined\n`,
        });
        return firstChild as any;
      })
      .mockImplementationOnce(() => {
        emitAndClose(secondChild, {
          code: 9,
          stdout: `${STATUS_PREFIX}invoke-error:ReferenceError: document is not defined\n`,
        });
        return secondChild as any;
      });

    const result = await printNativeIgnitionBytecode(
      {
        functionName: 'myFunc',
        sourceSlice: 'function myFunc() { return document.title; }',
      },
      100,
    );

    expect(result.available).toBe(false);
    expect(result.reason).toContain('Function compiled but raised during isolated invocation');
    expect(result.reason).toContain('ReferenceError: document is not defined');
  });

  it('prefers stderr text when the bytecode printer exits non-zero', async () => {
    const firstChild = createFakeChildProcess();
    const secondChild = createFakeChildProcess();

    mockSpawn
      .mockImplementationOnce(() => {
        emitAndClose(firstChild, {});
        return firstChild as any;
      })
      .mockImplementationOnce(() => {
        emitAndClose(secondChild, {
          code: 3,
          stderr: 'permission denied',
        });
        return secondChild as any;
      });

    const result = await printNativeIgnitionBytecode(
      {
        functionName: 'myFunc',
        sourceSlice: 'function myFunc() { return 1; }',
      },
      100,
    );

    expect(result.available).toBe(false);
    expect(result.reason).toBe('permission denied');
  });

  it('returns a timeout error when the printer never finishes', async () => {
    vi.useFakeTimers();
    const child = createFakeChildProcess();
    mockSpawn.mockImplementationOnce(() => child as any);

    const resultPromise = printNativeIgnitionBytecode(
      {
        functionName: 'anonymous',
        sourceSlice: '() => 1',
      },
      25,
    );

    await vi.advanceTimersByTimeAsync(25);
    const result = await resultPromise;

    expect(child.kill).toHaveBeenCalled();
    expect(result.available).toBe(false);
    expect(result.reason).toContain('Timed out after 25ms');
  });

  it('surfaces spawn errors from the isolated process', async () => {
    const firstChild = createFakeChildProcess();
    const secondChild = createFakeChildProcess();

    mockSpawn
      .mockImplementationOnce(() => {
        emitAndClose(firstChild, { error: new Error('spawn ENOENT') });
        return firstChild as any;
      })
      .mockImplementationOnce(() => {
        emitAndClose(secondChild, { error: new Error('spawn ENOENT') });
        return secondChild as any;
      });

    const result = await printNativeIgnitionBytecode(
      {
        functionName: 'myFunc',
        sourceSlice: 'function myFunc() { return 1; }',
      },
      100,
    );

    expect(result.available).toBe(false);
    expect(result.reason).toBe('spawn ENOENT');
  });

  it('returns a generic reason when no matching bytecode block is emitted', async () => {
    const firstChild = createFakeChildProcess();
    const secondChild = createFakeChildProcess();

    mockSpawn
      .mockImplementationOnce(() => {
        emitAndClose(firstChild, {
          stdout: [
            '[generated bytecode for function: otherFunc (0x123)]',
            'Bytecode length: 1',
            '0 @ Return',
            `${STATUS_PREFIX}done`,
            '',
          ].join('\n'),
        });
        return firstChild as any;
      })
      .mockImplementationOnce(() => {
        emitAndClose(secondChild, {
          stdout: [
            '[generated bytecode for function: stillOther (0x124)]',
            'Bytecode length: 1',
            '0 @ Return',
            `${STATUS_PREFIX}done`,
            '',
          ].join('\n'),
        });
        return secondChild as any;
      });

    const result = await printNativeIgnitionBytecode(
      {
        functionName: 'myFunc',
        sourceSlice: 'function myFunc() { return 1; }',
      },
      100,
    );

    expect(result.available).toBe(false);
    expect(result.reason).toContain('did not emit a matching function block');
  });
});
