import type { McpServer, RegisteredTool } from '@modelcontextprotocol/sdk/server/mcp.js';
import type { Server } from 'node:http';
import type { Socket } from 'node:net';
import type { Tool } from '@modelcontextprotocol/sdk/types.js';
import type { Config } from '../types/index.js';
import type { CodeCollector } from '../modules/collector/CodeCollector.js';
import type { PageController } from '../modules/collector/PageController.js';
import type { DOMInspector } from '../modules/collector/DOMInspector.js';
import type { ScriptManager } from '../modules/debugger/ScriptManager.js';
import type { DebuggerManager } from '../modules/debugger/DebuggerManager.js';
import type { RuntimeInspector } from '../modules/debugger/RuntimeInspector.js';
import type { ConsoleMonitor } from '../modules/monitor/ConsoleMonitor.js';
import type { BrowserToolHandlers } from './domains/browser/index.js';
import type { DebuggerToolHandlers } from './domains/debugger/index.js';
import type { AdvancedToolHandlers } from './domains/network/index.js';
import type { AIHookToolHandlers, HookPresetToolHandlers } from './domains/hooks/index.js';
import type { Deobfuscator } from '../modules/deobfuscator/Deobfuscator.js';
import type { AdvancedDeobfuscator } from '../modules/deobfuscator/AdvancedDeobfuscator.js';
import type { ASTOptimizer } from '../modules/deobfuscator/ASTOptimizer.js';
import type { ObfuscationDetector } from '../modules/detector/ObfuscationDetector.js';
import type { LLMService } from '../services/LLMService.js';
import type { CodeAnalyzer } from '../modules/analyzer/CodeAnalyzer.js';
import type { CryptoDetector } from '../modules/crypto/CryptoDetector.js';
import type { HookManager } from '../modules/hook/HookManager.js';
import type { TokenBudgetManager } from '../utils/TokenBudgetManager.js';
import type { UnifiedCacheManager } from '../utils/UnifiedCacheManager.js';
import type { CoreAnalysisHandlers } from './domains/analysis/index.js';
import type { CoreMaintenanceHandlers } from './domains/maintenance/index.js';
import type { ProcessToolHandlers } from './domains/process/index.js';
import type { WorkflowHandlers } from './domains/workflow/index.js';
import type { WasmToolHandlers } from './domains/wasm/index.js';
import type { StreamingToolHandlers } from './domains/streaming/index.js';
import type { EncodingToolHandlers } from './domains/encoding/index.js';
import type { AntiDebugToolHandlers } from './domains/antidebug/index.js';
import type { GraphQLToolHandlers } from './domains/graphql/index.js';
import type { PlatformToolHandlers } from './domains/platform/index.js';
import type { SourcemapToolHandlers } from './domains/sourcemap/index.js';
import type { TransformToolHandlers } from './domains/transform/index.js';
import type { ToolArgs, ToolResponse } from './types.js';
import type { ToolDomain, ToolProfile } from './ToolCatalog.js';
import type { ToolExecutionRouter } from './ToolExecutionRouter.js';
import type { ToolHandlerMapDependencies } from './ToolHandlerMap.js';

export interface MCPServerContext {
  config: Config;
  server: McpServer;
  tokenBudget: TokenBudgetManager;
  unifiedCache: UnifiedCacheManager;
  selectedTools: Tool[];
  enabledDomains: Set<ToolDomain>;
  router: ToolExecutionRouter;
  handlerDeps: ToolHandlerMapDependencies;
  baseTier: ToolProfile;
  currentTier: ToolProfile;
  boostHistory: ToolProfile[];
  boostedToolNames: Set<string>;
  boostedRegisteredTools: Map<string, RegisteredTool>;
  boostTtlTimer: ReturnType<typeof setTimeout> | null;
  boostLock: Promise<void>;
  httpServer?: Server;
  httpSockets: Set<Socket>;
  collector?: CodeCollector;
  pageController?: PageController;
  domInspector?: DOMInspector;
  scriptManager?: ScriptManager;
  debuggerManager?: DebuggerManager;
  runtimeInspector?: RuntimeInspector;
  consoleMonitor?: ConsoleMonitor;
  llm?: LLMService;
  browserHandlers?: BrowserToolHandlers;
  debuggerHandlers?: DebuggerToolHandlers;
  advancedHandlers?: AdvancedToolHandlers;
  aiHookHandlers?: AIHookToolHandlers;
  hookPresetHandlers?: HookPresetToolHandlers;
  deobfuscator?: Deobfuscator;
  advancedDeobfuscator?: AdvancedDeobfuscator;
  astOptimizer?: ASTOptimizer;
  obfuscationDetector?: ObfuscationDetector;
  analyzer?: CodeAnalyzer;
  cryptoDetector?: CryptoDetector;
  hookManager?: HookManager;
  coreAnalysisHandlers?: CoreAnalysisHandlers;
  coreMaintenanceHandlers?: CoreMaintenanceHandlers;
  processHandlers?: ProcessToolHandlers;
  workflowHandlers?: WorkflowHandlers;
  wasmHandlers?: WasmToolHandlers;
  streamingHandlers?: StreamingToolHandlers;
  encodingHandlers?: EncodingToolHandlers;
  antidebugHandlers?: AntiDebugToolHandlers;
  graphqlHandlers?: GraphQLToolHandlers;
  platformHandlers?: PlatformToolHandlers;
  sourcemapHandlers?: SourcemapToolHandlers;
  transformHandlers?: TransformToolHandlers;
  registerCaches(): Promise<void>;
  resolveEnabledDomains(tools: Tool[]): Set<ToolDomain>;
  registerSingleTool(toolDef: Tool): RegisteredTool;
  boostProfile(target?: string, ttlMinutes?: number): Promise<Record<string, unknown>>;
  unboostProfile(target?: string): Promise<Record<string, unknown>>;
  switchToTier(targetTier: ToolProfile): Promise<void>;
  executeToolWithTracking(name: string, args: ToolArgs): Promise<ToolResponse>;
}
