import type { MCPServerContext } from '@server/MCPServer.context';
import { generateAntiDebugBypass } from '@modules/hook/HookGeneratorBuilders.core';
import { getInjectionInstructions } from '@modules/hook/HookGeneratorBuilders.core';

export function registerServerPrompts(ctx: MCPServerContext): void {
  // 1. Reverse Engineering Assistant System Prompt
  ctx.server.prompt(
    'reverse_engineering_assistant',
    'System prompt and guidelines for using jshookmcp tools effectively.',
    () => ({
      messages: [
        {
          role: 'assistant',
          content: {
            type: 'text',
            text: `I am a JS reverse engineer assistant equipped with the jshookmcp toolkit.
I have access to instrumentation tools, AST flattening engines, and memory scanners.
When analyzing a target:
1. I will use the browser domains to attach to pages and locate heavily obfuscated scripts.
2. I will use the transform and deobfuscate tools to simplify JSVMP or Obfuscator.io structures before making assumptions.
3. If I encounter debugger traps, I will recommend the anti-debug bypass prompt or tools.
How can I help you reverse engineer your target today?`,
          },
        },
      ],
    }),
  );

  // 2. Anti-Debug Analysis Runbook
  ctx.server.prompt(
    'analyze_anti_debug',
    'Runbook and scripts for defeating debugger protections and traps.',
    () => ({
      messages: [
        {
          role: 'user',
          content: {
            type: 'text',
            text: 'I am encountering infinite debugger loops and anti-tamper traps. What should I do?',
          },
        },
        {
          role: 'assistant',
          content: {
            type: 'text',
            text: `To defeat common anti-debugging techniques, inject the following bypass script prior to page load (using page_evaluateOnNewDocument if possible):

\`\`\`javascript
${generateAntiDebugBypass()}
\`\`\`

If execution still halts, use the 'memory_scan' tool with pattern 'debugger' or use the AST flattening tools on the suspected control-flow-flattened script.`,
          },
        },
      ],
    }),
  );

  // 3. Hook Generation Guide
  ctx.server.prompt(
    'hook_generation_guide',
    'Instructions on how to deploy and use hooks generated by the hook builder.',
    () => ({
      messages: [
        {
          role: 'user',
          content: {
            type: 'text',
            text: 'How do I use generated function or storage hooks?',
          },
        },
        {
          role: 'assistant',
          content: {
            type: 'text',
            text: `${getInjectionInstructions('function')}

Generally, you have three options to deploy hooks:
1.  **Immediate Execution**: Use the \`console_execute\` tool in the browser domain to run the generated hook script immediately on the active page.
2.  **Early Injection**: Use \`page_evaluateOnNewDocument\` to ensure the hook is installed before any target website scripts execute.
3.  **Local Overrides**: Save the hook script via \`write_file\` and use browser overrides (or proxy mapping) to serve it in place of the original file.`,
          },
        },
      ],
    }),
  );
}
