import { spawn } from 'node:child_process';

const STATUS_PREFIX = '__JSHOOK_BYTECODE_STATUS__:';
const TARGET_NAME = '__jshookBytecodeTarget__';
const DEFAULT_TIMEOUT_MS = 15_000;

export interface NativeSourceContext {
  functionName: string;
  sourceSlice: string;
}

export interface IsolatedNativeBytecodeAttempt {
  available: boolean;
  bytecode: string | null;
  format: 'ignition-bytecode' | null;
  functionName: string;
  reason: string;
  rawIgnitionBytecodeAvailable: boolean;
}

function isValidFunctionName(value: string): boolean {
  return /^[A-Za-z_$][\w$]*$/u.test(value);
}

function normalizeFunctionName(value: string): string {
  const trimmed = value.trim();
  if (trimmed.length === 0 || trimmed === 'anonymous') {
    return TARGET_NAME;
  }
  return isValidFunctionName(trimmed) ? trimmed : TARGET_NAME;
}

function shouldWrapAsObjectMember(source: string): boolean {
  const trimmed = source.trim();
  if (
    trimmed.startsWith('function') ||
    trimmed.startsWith('async function') ||
    trimmed.startsWith('class ') ||
    trimmed.startsWith('(') ||
    trimmed.includes('=>')
  ) {
    return false;
  }
  return /^(?:async\s+)?(?:get\s+|set\s+)?\*?\s*[A-Za-z_$][\w$]*\s*\(/u.test(trimmed);
}

function buildBootstrapScript(context: NativeSourceContext): string {
  const source = context.sourceSlice.trim();
  const requestedName = context.functionName.trim();
  const bindingCode = shouldWrapAsObjectMember(source)
    ? `
try {
  const __jshookHolder = { ${source} };
  const __jshookCandidate = __jshookHolder[${JSON.stringify(requestedName)}];
  if (typeof __jshookCandidate === 'function') {
    ${TARGET_NAME} = __jshookCandidate;
  }
} catch {}
`
    : `
try {
  ${TARGET_NAME} = (${source});
} catch {}
`;

  return `
let ${TARGET_NAME};
${bindingCode}

if (typeof ${TARGET_NAME} !== 'function') {
  console.log(${JSON.stringify(`${STATUS_PREFIX}resolve-failed`)});
} else {
  try {
    const __jshookArity =
      typeof ${TARGET_NAME}.length === 'number' && ${TARGET_NAME}.length > 0
        ? ${TARGET_NAME}.length
        : 0;
    Reflect.apply(${TARGET_NAME}, globalThis, Array.from({ length: __jshookArity }, () => undefined));
  } catch (error) {
    console.log(${JSON.stringify(`${STATUS_PREFIX}invoke-error:`)} + String(error));
  }
  console.log(${JSON.stringify(`${STATUS_PREFIX}done`)});
}
`;
}

function parsePrintedBytecode(
  output: string,
  candidateNames: readonly string[],
): { bytecode: string | null; matchedFunctionName: string | null } {
  const lines = output.split(/\r?\n/u);
  const filters = new Set(candidateNames.filter((entry) => entry.length > 0));
  let matchedFunctionName: string | null = null;
  let capturing = false;
  const captured: string[] = [];

  for (const line of lines) {
    const headerMatch = /^\[generated bytecode for function: (.+?) \(/u.exec(line);
    if (headerMatch?.[1]) {
      if (capturing && captured.length > 0) {
        break;
      }
      matchedFunctionName = filters.has(headerMatch[1]) ? headerMatch[1] : null;
      capturing = matchedFunctionName !== null;
      if (capturing) {
        captured.length = 0;
        captured.push(line);
      }
      continue;
    }

    if (!capturing) {
      continue;
    }
    if (line.startsWith(STATUS_PREFIX)) {
      break;
    }
    captured.push(line);
  }

  if (captured.length === 0) {
    return { bytecode: null, matchedFunctionName: null };
  }
  return { bytecode: captured.join('\n').trim(), matchedFunctionName };
}

function parseStatus(output: string): string | null {
  const line = output
    .split(/\r?\n/u)
    .find((entry) => entry.startsWith(STATUS_PREFIX) && entry.length > STATUS_PREFIX.length);
  return line ? line.slice(STATUS_PREFIX.length) : null;
}

function formatIsolatedFailure(output: string, stderr: string, fallback: string): string {
  const status = parseStatus(output);
  if (status === 'resolve-failed') {
    return 'Unable to reconstruct an executable function from the captured source slice';
  }
  if (typeof status === 'string' && status.startsWith('invoke-error:')) {
    return `Function compiled but raised during isolated invocation: ${status.slice('invoke-error:'.length)}`;
  }
  const stderrText = stderr.trim();
  if (stderrText.length > 0) {
    return stderrText;
  }
  return fallback;
}

async function runBytecodePrinter(
  bootstrapScript: string,
  filterName: string,
  timeoutMs: number,
): Promise<{ stdout: string; stderr: string; error: string | null }> {
  return await new Promise((resolve) => {
    const child = spawn(
      process.execPath,
      ['--print-bytecode', `--print-bytecode-filter=${filterName}`, '-'],
      {
        stdio: ['pipe', 'pipe', 'pipe'],
      },
    );

    let stdout = '';
    let stderr = '';
    let settled = false;

    const finish = (error: string | null) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolve({ stdout, stderr, error });
    };

    const timer = setTimeout(() => {
      child.kill();
      finish(`Timed out after ${timeoutMs}ms while waiting for isolated bytecode output`);
    }, timeoutMs);

    child.stdout.setEncoding('utf8');
    child.stderr.setEncoding('utf8');
    child.stdout.on('data', (chunk: string) => {
      stdout += chunk;
    });
    child.stderr.on('data', (chunk: string) => {
      stderr += chunk;
    });
    child.on('error', (error) => {
      finish(error instanceof Error ? error.message : String(error));
    });
    child.on('close', (code) => {
      finish(code === 0 ? null : `Bytecode printer exited with code ${code}`);
    });
    child.stdin.end(bootstrapScript);
  });
}

export async function printNativeIgnitionBytecode(
  context: NativeSourceContext,
  timeoutMs: number = DEFAULT_TIMEOUT_MS,
): Promise<IsolatedNativeBytecodeAttempt> {
  const requestedName = normalizeFunctionName(context.functionName);
  const candidateNames = Array.from(new Set([requestedName, TARGET_NAME]));
  const bootstrapScript = buildBootstrapScript(context);

  for (const filterName of candidateNames) {
    const { stdout, stderr, error } = await runBytecodePrinter(
      bootstrapScript,
      filterName,
      timeoutMs,
    );
    const extracted = parsePrintedBytecode(stdout, candidateNames);
    if (extracted.bytecode) {
      const resolvedFunctionName =
        extracted.matchedFunctionName === TARGET_NAME
          ? requestedName
          : extracted.matchedFunctionName;
      return {
        available: true,
        bytecode: extracted.bytecode,
        format: 'ignition-bytecode',
        functionName: resolvedFunctionName ?? requestedName,
        reason:
          'Ignition bytecode emitted by an isolated V8 process via --print-bytecode from the extracted source slice',
        rawIgnitionBytecodeAvailable: true,
      };
    }
    if (error && filterName === candidateNames.at(-1)) {
      return {
        available: false,
        bytecode: null,
        format: null,
        functionName: requestedName,
        reason: formatIsolatedFailure(stdout, stderr, error),
        rawIgnitionBytecodeAvailable: false,
      };
    }
  }

  return {
    available: false,
    bytecode: null,
    format: null,
    functionName: requestedName,
    reason: 'Isolated V8 bytecode printer did not emit a matching function block',
    rawIgnitionBytecodeAvailable: false,
  };
}
