verbose = "info"
no_progress = true
exclude = [
  "^http://127\\.0\\.0\\.1",
  "^http://localhost",
  "^ws://127\\.0\\.0\\.1",
  "^ws://localhost",
  "^D:\\\\coding\\\\reverse\\\\"
]
exclude_path = [
  "docs/.vitepress/dist/assets/**",
  "docs/.vitepress/dist/hashmap.json",
  "docs/.vitepress/dist/vp-icons.css",
  "node_modules/**",
  "artifacts/**"
]
