import type { E2EContext, E2EConfig } from '@tests/e2e/helpers/types';

export function getOverrides(
  ctx: E2EContext,
  config: E2EConfig
): Record<string, Record<string, unknown>> {
  const { targetUrl, targetDomain, artifactDir, browserPath, asarPath, electronPath, miniappPath } =
    config;

  return {
    browser_launch: { headless: false },
    browser_attach: { endpoint: 'http://localhost:9222' },
    page_navigate: { url: targetUrl, waitUntil: 'load', timeout: 15000 },
    page_evaluate: { code: 'document.title' },
    page_click: { selector: 'body' },
    page_type: { selector: 'body', text: 'e2e' },
    page_select: { selector: '#test_select_e2e', values: ['b'] },
    page_hover: { selector: 'body' },
    page_scroll: { direction: 'down', amount: 100 },
    page_press_key: { key: 'Escape' },
    page_wait_for_selector: { selector: 'body', timeout: 3000 },
    page_inject_script: { script: 'window.__e2e_injected = true;' },
    page_set_viewport: { width: 1280, height: 720 },
    page_emulate_device: { device: 'iPhone 14' },
    page_set_cookies: { cookies: [{ name: 'e2e', value: '1', domain: targetDomain }] },
    page_set_local_storage: { key: 'e2e_test', value: 'hello' },
    page_back: {},
    page_forward: {},
    page_reload: {},
    page_screenshot: {
      selector: ['.VPNav', '.VPHero', '.VPFeatures'],
      path: `${artifactDir}/screenshot.png`,
    },
    page_script_register: { name: 'e2e_lib', code: 'function e2eHelper() { return 42; }' },
    page_script_run: { name: 'e2e_lib' },
    dom_query_selector: { selector: 'body' },
    dom_query_all: { selector: 'div' },
    dom_get_structure: { selector: 'body', depth: 2 },
    dom_find_clickable: {},
    dom_find_by_text: { text: 'test' },
    dom_get_xpath: { selector: 'body' },
    dom_is_in_viewport: { selector: 'body' },
    dom_get_computed_style: { selector: 'body' },
    console_enable: { enableNetwork: true },
    console_execute: { expression: '1+1' },
    console_inject_function_tracer: { functionName: 'fetch' },
    debugger_evaluate: { expression: '1+1' },
    debugger_evaluate_global: { expression: 'document.title' },
    debugger_wait_for_paused: { timeout: 3000 },
    breakpoint_set: ctx.scriptId
      ? { scriptId: ctx.scriptId, lineNumber: 1 }
      : { url: targetUrl, lineNumber: 1 },
    breakpoint_remove: { breakpointId: ctx.breakpointId || '__placeholder__' },
    get_all_scripts: {},
    get_script_source: { url: targetUrl },
    get_detailed_data: { detailId: ctx.detailId || '__placeholder__' },
    breakpoint_set_on_exception: { state: 'all' },
    breakpoint_list: {},
    xhr_breakpoint_set: { urlPattern: '/api/' },
    xhr_breakpoint_list: {},
    event_breakpoint_set: { eventName: 'click' },
    event_breakpoint_set_category: { category: 'mouse' },
    event_breakpoint_list: {},
    watch_add: { expression: 'window.location.href' },
    watch_list: {},
    watch_evaluate_all: {},
    get_scope_variables_enhanced: {},
    debugger_get_paused_state: {},
    debugger_step_into: {},
    debugger_step_out: {},
    network_enable: {},
    network_get_requests: {},
    network_get_response_body: { requestId: ctx.requestId || '__placeholder__' },
    network_get_stats: {},
    network_get_status: {},
    network_extract_auth: {},
    network_export_har: { path: `${artifactDir}/network.har` },
    network_replay_request: { requestId: ctx.requestId || '__placeholder__' },
    performance_get_metrics: {},
    performance_trace_stop: {},
    profiler_cpu_stop: {},
    profiler_heap_sampling_stop: {},
    performance_stop_coverage: {},
    performance_take_heap_snapshot: {},
    ws_monitor_enable: {},
    sse_monitor_enable: {},
    ws_get_frames: {},
    ws_get_connections: {},
    sse_get_events: {},
    binary_detect_format: { data: 'SGVsbG8=', source: 'base64' },
    binary_decode: { data: 'SGVsbG8=', encoding: 'base64' },
    binary_encode: { data: 'Hello', inputFormat: 'utf8', outputEncoding: 'base64' },
    binary_entropy_analysis: { data: 'SGVsbG8gV29ybGQ=', source: 'base64' },
    protobuf_decode_raw: { data: 'CAESBXdvcmxk' },
    manage_hooks: { action: 'list' },
    ai_hook_generate: {
      target: { type: 'api', name: 'fetch' },
      description: 'log fetch calls',
      behavior: { captureArgs: true, captureReturn: true },
    },
    ai_hook_inject: { hookId: ctx.hookId || '__placeholder__', code: 'console.log("e2e hook")' },
    ai_hook_toggle: { hookId: ctx.hookId || '__placeholder__', enabled: true },
    ai_hook_get_data: { hookId: ctx.hookId || '__placeholder__' },
    ai_hook_export: {},
    ai_hook_clear: {},
    ai_hook_list: {},
    hook_preset: { preset: 'network_monitor' },
    deobfuscate: { code: 'var a = 1;' },
    advanced_deobfuscate: { code: 'var a = 1;' },
    webcrack_unpack: { code: 'var a = 1;' },
    understand_code: { code: 'function add(a,b){return a+b}' },
    detect_obfuscation: { code: 'eval(atob("YWxlcnQoMSk="))' },
    detect_crypto: { code: 'crypto.subtle.digest("SHA-256", data)' },
    search_in_scripts: { keyword: 'fetch' },
    collect_code: { url: targetUrl, returnSummaryOnly: true },
    graphql_introspect: { endpoint: targetUrl },
    graphql_extract_queries: {},
    graphql_replay: { endpoint: targetUrl, query: '{ __typename }' },
    script_replace_persist: { url: '__never_match_e2e__', replacement: '// replaced' },
    call_graph_analyze: { code: 'function a(){b()} function b(){return 1}' },
    ast_transform_preview: { code: 'var a = 1;', transforms: ['rename_vars'] },
    ast_transform_apply: { code: 'var a = 1;', transforms: ['rename_vars'] },
    ast_transform_chain: { name: 'e2e_chain', transforms: ['rename_vars'] },
    crypto_compare: {
      code1: 'function encrypt(a){return a}',
      code2: 'function encrypt(a){return a}',
      functionName: 'encrypt',
      testInputs: ['test'],
    },
    crypto_extract_standalone: { targetFunction: 'CryptoJS.AES.encrypt' },
    crypto_test_harness: {
      code: 'function encrypt(d){return d}',
      functionName: 'encrypt',
      testInputs: ['test'],
    },
    blackbox_add: { urlPattern: '/node_modules/' },
    process_get: { pid: 0 },
    process_list: {},
    process_windows: { pid: 0 },
    process_find: { pattern: 'browser' },
    process_find_chromium: {},
    process_launch_debug: { executablePath: browserPath, debugPort: 19222, args: ['--headless'] },
    process_check_debug_port: { pid: 0 },
    wasm_dump: { url: targetUrl },
    wasm_decompile: { inputPath: '__placeholder__.wasm' },
    wasm_disassemble: { inputPath: '__placeholder__.wasm' },
    wasm_inspect_sections: { inputPath: '__placeholder__.wasm' },
    wasm_memory_inspect: {},
    wasm_optimize: { inputPath: '__placeholder__.wasm' },
    wasm_vmp_trace: {},
    antidebug_detect_protections: {},
    antidebug_bypass_all: {},
    antidebug_bypass_debugger_statement: {},
    antidebug_bypass_console_detect: {},
    antidebug_bypass_stack_trace: {},
    antidebug_bypass_timing: {},
    source_map_extract: { url: targetUrl },
    sourcemap_fetch_and_parse: { sourceMapUrl: targetUrl },
    sourcemap_reconstruct_tree: { sourceMapUrl: targetUrl },
    sourcemap_discover: {},
    extension_list_installed: {},
    stealth_inject: {},
    stealth_set_user_agent: {
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Browser/120.0.0.0',
    },
    captcha_detect: {},
    captcha_config: { provider: '2captcha', apiKey: 'test' },
    camoufox_server_status: {},
    browser_select_tab: { index: 0 },
    tab_workflow: { action: 'list' },
    webpack_enumerate: {},
    js_heap_search: { pattern: 'fetch' },
    indexeddb_dump: {},
    framework_state_extract: {},
    get_object_properties: { objectId: ctx.objectId || '__placeholder__' },
    web_api_capture_session: { url: targetUrl },
    api_probe_batch: { baseUrl: targetUrl, paths: ['/'] },
    js_bundle_search: { url: targetUrl, patterns: [{ name: 'fetch_calls', regex: 'fetch\\(' }] },
    get_token_budget_stats: {},
    get_cache_stats: {},
    get_collection_stats: {},
    boost_profile: { profile: 'full' },
    unboost_profile: {},
    asar_extract: asarPath ? { inputPath: asarPath } : {},
    electron_inspect_app: { appPath: electronPath || '__placeholder__' },
    miniapp_pkg_scan: { searchPath: miniappPath || '__placeholder__' },
    miniapp_pkg_unpack: { inputPath: miniappPath || '__placeholder__' },
    miniapp_pkg_analyze: { unpackedDir: miniappPath || '__placeholder__' },
    memory_check_protection: { pid: 0, address: '0x0' },
    memory_read: { pid: 0, address: '0x0', size: 16 },
    memory_scan: { pid: 0, pattern: 'test' },
    memory_scan_filtered: { pid: 0, pattern: 'test', addresses: ['0x0'] },
    memory_audit_export: { pid: 0, outputPath: `${artifactDir}/memory-audit.json` },
    human_mouse: { selector: 'body' },
    human_scroll: { direction: 'down', amount: 200 },
    human_typing: { selector: 'body', text: 'e2e' },
    captcha_vision_solve: {},
    widget_challenge_solve: {},
    list_extensions: {},
    reload_extensions: {},
    browse_extension_registry: {},
    batch_register: {
      registerUrl: targetUrl,
      accounts: [{ fields: { email: 'e2e@test.local', password: 'Test123!' } }],
    },
    list_extension_workflows: {},
    run_extension_workflow: { workflowId: ctx.workflowId ?? '__placeholder__' },
  };
}
