// AUTO-GENERATED BY scripts/generate-domains-index.mjs
// DO NOT EDIT DIRECTLY

import manifest_0 from '../domains/adb-bridge/manifest.js';
import manifest_1 from '../domains/analysis/manifest.js';
import manifest_2 from '../domains/antidebug/manifest.js';
import manifest_3 from '../domains/binary-instrument/manifest.js';
import manifest_4 from '../domains/boringssl-inspector/manifest.js';
import manifest_5 from '../domains/browser/manifest.js';
import manifest_6 from '../domains/canvas/manifest.js';
import manifest_7 from '../domains/coordination/manifest.js';
import manifest_8 from '../domains/cross-domain/manifest.js';
import manifest_9 from '../domains/debugger/manifest.js';
import manifest_10 from '../domains/encoding/manifest.js';
import manifest_11 from '../domains/evidence/manifest.js';
import manifest_12 from '../domains/extension-registry/manifest.js';
import manifest_13 from '../domains/graphql/manifest.js';
import manifest_14 from '../domains/hooks/manifest.js';
import manifest_15 from '../domains/instrumentation/manifest.js';
import manifest_16 from '../domains/macro/manifest.js';
import manifest_17 from '../domains/maintenance/manifest.js';
import manifest_18 from '../domains/memory/manifest.js';
import manifest_19 from '../domains/mojo-ipc/manifest.js';
import manifest_20 from '../domains/network/manifest.js';
import manifest_21 from '../domains/platform/manifest.js';
import manifest_22 from '../domains/process/manifest.js';
import manifest_23 from '../domains/protocol-analysis/manifest.js';
import manifest_24 from '../domains/sandbox/manifest.js';
import manifest_25 from '../domains/shared-state-board/manifest.js';
import manifest_26 from '../domains/skia-capture/manifest.js';
import manifest_27 from '../domains/sourcemap/manifest.js';
import manifest_28 from '../domains/streaming/manifest.js';
import manifest_29 from '../domains/syscall-hook/manifest.js';
import manifest_30 from '../domains/trace/manifest.js';
import manifest_31 from '../domains/transform/manifest.js';
import manifest_32 from '../domains/v8-inspector/manifest.js';
import manifest_33 from '../domains/wasm/manifest.js';
import manifest_34 from '../domains/workflow/manifest.js';

export const generatedManifests = [
  manifest_0,
  manifest_1,
  manifest_2,
  manifest_3,
  manifest_4,
  manifest_5,
  manifest_6,
  manifest_7,
  manifest_8,
  manifest_9,
  manifest_10,
  manifest_11,
  manifest_12,
  manifest_13,
  manifest_14,
  manifest_15,
  manifest_16,
  manifest_17,
  manifest_18,
  manifest_19,
  manifest_20,
  manifest_21,
  manifest_22,
  manifest_23,
  manifest_24,
  manifest_25,
  manifest_26,
  manifest_27,
  manifest_28,
  manifest_29,
  manifest_30,
  manifest_31,
  manifest_32,
  manifest_33,
  manifest_34,
];
