/**
 * Live eBPF Attach Handler — syscall_ebpf_attach
 *
 * Unlike syscall_ebpf_trace (which generates bpftrace scripts for manual
 * execution), this handler actually spawns a bpftrace child process, captures
 * the NDJSON stdout stream, and returns structured SyscallEvent objects
 * directly — no separate copy/paste/run step required.
 *
 * When live bpftrace is unavailable (non-Linux, no bpftrace binary, or
 * insufficient privileges), it falls back to script-output mode (same as
 * syscall_ebpf_trace) with a clear capability diagnostic.
 */

import { argNumber, argStringArray } from '@server/domains/shared/parse-args';
import type { SyscallEvent } from '@modules/syscall-hook';

// ── Types ──────────────────────────────────────────────────────────────────────

export interface EbpfAttachResult {
  success: boolean;
  error?: string;
  mode: 'live' | 'script' | 'simulated';
  pid: number;
  durationSec: number;
  syscallsTraced: string[];
  events?: SyscallEvent[];
  eventCount: number;
  /** When mode=script, the bpftrace script to execute. */
  script?: string;
  /** Usage instructions (for script mode). */
  usage?: string;
  /** Whether the platform can do live bpftrace attach. */
  liveCapable: boolean;
  /** Whether bpftrace binary was found. */
  bpftraceAvailable: boolean;
  /** Explicit watermark for simulated data. */
  isSimulated?: boolean;
}

// ── Constants ──────────────────────────────────────────────────────────────────

const TRACE_DURATION_MIN_SEC = 1;
const TRACE_DURATION_MAX_SEC = 300;
const DEFAULT_TRACE_DURATION_SEC = 10;
const DEFAULT_SYSCALLS = [
  'read',
  'write',
  'openat',
  'close',
  'fstat',
  'mmap',
  'mprotect',
  'munmap',
  'brk',
  'ioctl',
  'connect',
  'sendto',
  'recvfrom',
  'clone',
  'execve',
];

// ── Helpers ────────────────────────────────────────────────────────────────────

function isValidSyscallName(name: string): boolean {
  const NAME_RE = /^[a-z][a-z0-9_]*$/;
  return NAME_RE.test(name) && name.length <= 64;
}

function isArgBool(args: Record<string, unknown>, key: string): boolean {
  return args[key] === true;
}

/**
 * Build a bpftrace script for the given pid + syscall filter + duration.
 * Mirrors the script generation in SyscallHookHandlers.handleSyscallEbpfTrace
 * but outputs raw JSONL (one JSON object per line) to stdout for machine
 * consumption.
 */
export function buildBpftraceScript(pid: number, syscalls: string[], durationSec: number): string {
  const pidFilter = pid > 0 ? `/pid == ${pid}/` : '';
  const tracepoints = syscalls.map((sc) => `tracepoint:syscalls:sys_enter_${sc}`).join(', ');
  const exitTracepoints = syscalls.map((sc) => `tracepoint:syscalls:sys_exit_${sc}`).join(', ');

  return `#!/usr/bin/env bpftrace
// Generated by jshookmcp syscall_ebpf_attach
// Target PID: ${pid || 'all'} | Duration: ${durationSec}s | Syscalls: ${syscalls.join(', ')}

BEGIN {
  printf("{\\"type\\":\\"start\\",\\"targetPid\\":%d,\\"durationSec\\":%d,\\"syscalls\\":[%s]}\\n",
    ${pid || 0}, ${durationSec}, "${syscalls.join('","')}");
}

${tracepoints} ${pidFilter}
{
  @enter_ts[tid] = nsecs;
  printf("{\\"type\\":\\"enter\\",\\"elapsedMs\\":%llu,\\"pid\\":%d,\\"tid\\":%d,\\"syscall\\":\\"%s\\",\\"args\\":\\"\\"",
    elapsed / 1000000, pid, tid, probe);
  if (probe == "tracepoint:syscalls:sys_enter_openat" || probe == "tracepoint:syscalls:sys_enter_open") {
    printf("\\"pathname\\": \\"%s\\", \\"flags\\": %d, \\"mode\\": %d", str(args->pathname), args->flags, args->mode);
  } else if (probe == "tracepoint:syscalls:sys_enter_read" || probe == "tracepoint:syscalls:sys_enter_write") {
    printf("\\"fd\\": %d, \\"count\\": %d", args->fd, args->count);
  } else if (probe == "tracepoint:syscalls:sys_enter_connect") {
    printf("\\"fd\\": %d", args->fd);
  } else if (probe == "tracepoint:syscalls:sys_enter_mmap") {
    printf("\\"addr\\": %llu, \\"length\\": %llu, \\"prot\\": %d, \\"flags\\": %d, \\"fd\\": %d",
      args->addr, args->length, args->prot, args->flags, args->fd);
  } else if (probe == "tracepoint:syscalls:sys_enter_execve") {
    printf("\\"filename\\": \\"%s\\"", str(args->filename));
  }
  printf("\\"}\\n");
}

${exitTracepoints} ${pidFilter}
{
  $elapsed_ns = nsecs - @enter_ts[tid];
  printf("{\\"type\\":\\"exit\\",\\"elapsedMs\\":%llu,\\"pid\\":%d,\\"tid\\":%d,\\"syscall\\":\\"%s\\",\\"ret\\":%d,\\"durationUs\\":%llu}\\n",
    elapsed / 1000000, pid, tid, probe, args->ret, $elapsed_ns / 1000);
  delete(@enter_ts[tid]);
}

interval:s:${durationSec} {
  printf("{\\"type\\":\\"stop\\",\\"elapsedMs\\":%llu}\\n", elapsed / 1000000);
  exit();
}

END {
  printf("{\\"type\\":\\"end\\",\\"elapsedMs\\":%llu}\\n", elapsed / 1000000);
  clear(@enter_ts);
}
`;
}

/**
 * Parse bpftrace JSONL stdout lines into structured events.
 * Handles enter/exit pair correlation.
 */
function parseBpftraceJsonl(
  lines: string[],
  pid: number,
  syscalls: string[],
): {
  events: SyscallEvent[];
  warnings: string[];
  enterCount: number;
  exitCount: number;
} {
  const events: SyscallEvent[] = [];
  const warnings: string[] = [];
  let enterCount = 0;
  let exitCount = 0;
  // Map tid → last enter entry for pairing
  const pendingEntries = new Map<
    number,
    { elapsedMs: number; pid: number; syscall: string; args: string[] }
  >();

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    let parsed: Record<string, unknown>;
    try {
      parsed = JSON.parse(trimmed) as Record<string, unknown>;
    } catch {
      warnings.push(`Unparseable bpftrace line: ${trimmed.substring(0, 80)}`);
      continue;
    }

    const type = typeof parsed['type'] === 'string' ? parsed['type'] : undefined;
    if (type === 'start' || type === 'stop' || type === 'end') continue;

    if (type === 'enter') {
      enterCount++;
      const tid = typeof parsed['tid'] === 'number' ? parsed['tid'] : undefined;
      const elapsedMs = typeof parsed['elapsedMs'] === 'number' ? parsed['elapsedMs'] : undefined;
      const eventPid = typeof parsed['pid'] === 'number' ? parsed['pid'] : pid;
      const syscall = extractSyscallName(
        typeof parsed['syscall'] === 'string' ? parsed['syscall'] : '',
        syscalls,
      );
      if (!syscall || tid === undefined || elapsedMs === undefined) continue;

      const args = extractEnterArgs(parsed);
      pendingEntries.set(tid, { elapsedMs, pid: eventPid, syscall, args });
    } else if (type === 'exit') {
      exitCount++;
      const tid = typeof parsed['tid'] === 'number' ? parsed['tid'] : undefined;
      const elapsedMs = typeof parsed['elapsedMs'] === 'number' ? parsed['elapsedMs'] : undefined;
      const ret = typeof parsed['ret'] === 'number' ? parsed['ret'] : undefined;
      const durationUs =
        typeof parsed['durationUs'] === 'number' ? parsed['durationUs'] : undefined;
      const syscallName = extractSyscallName(
        typeof parsed['syscall'] === 'string' ? parsed['syscall'] : '',
        syscalls,
      );

      if (tid === undefined || elapsedMs === undefined) continue;

      const enter = pendingEntries.get(tid);
      const syscall = enter?.syscall ?? syscallName ?? 'unknown';
      const args = enter?.args ?? [];
      const pidForEvent = enter?.pid ?? (typeof parsed['pid'] === 'number' ? parsed['pid'] : pid);

      pendingEntries.delete(tid);

      events.push({
        timestamp: elapsedMs,
        pid: pidForEvent,
        syscall,
        args,
        returnValue: ret,
        duration: durationUs !== undefined ? durationUs / 1000 : undefined, // μs → ms
      });
    }
  }

  // Flush unmatched enter events as partial entries
  for (const [, enter] of pendingEntries) {
    events.push({
      timestamp: enter.elapsedMs,
      pid: enter.pid,
      syscall: enter.syscall,
      args: enter.args,
    });
  }

  return { events, warnings, enterCount, exitCount };
}

function extractSyscallName(probe: string, syscalls: string[]): string | undefined {
  // probe looks like "tracepoint:syscalls:sys_enter_read" or "tracepoint:syscalls:sys_exit_read"
  const match = /sys_(?:enter|exit)_(\w+)$/.exec(probe);
  if (!match) return undefined;
  const name = match[1]!;
  return syscalls.includes(name) ? name : name;
}

function extractEnterArgs(parsed: Record<string, unknown>): string[] {
  const args: string[] = [];
  // Common args from the bpftrace script
  for (const key of [
    'pathname',
    'fd',
    'count',
    'flags',
    'mode',
    'addr',
    'length',
    'prot',
    'filename',
  ]) {
    const val = parsed[key];
    if (typeof val === 'string') args.push(`${key}=${val}`);
    else if (typeof val === 'number') args.push(`${key}=${val}`);
  }
  return args;
}

/**
 * Detect whether bpftrace is available on this system.
 */
async function probeBpftrace(): Promise<{
  available: boolean;
  liveCapable: boolean;
  reason?: string;
}> {
  // Only Linux can do live bpftrace
  if (process.platform !== 'linux') {
    return {
      available: false,
      liveCapable: false,
      reason: `Platform ${process.platform} does not support bpftrace`,
    };
  }

  try {
    const { execFile } = await import('node:child_process');
    const { promisify } = await import('node:util');
    const execFileAsync = promisify(execFile);
    const { stdout } = await execFileAsync('bpftrace', ['--version'], { timeout: 5000 });
    const version = stdout.trim();
    return {
      available: version.length > 0,
      liveCapable: true,
    };
  } catch {
    return {
      available: false,
      liveCapable: true, // Linux is capable, bpftrace just isn't installed
      reason:
        'bpftrace binary not found. Install with: apt install bpftrace (Debian/Ubuntu) or equivalent.',
    };
  }
}

/**
 * Spawn bpftrace live and parse its JSONL output.
 * Requires Linux with bpftrace + CAP_BPF or root.
 */
async function captureLiveBpftrace(
  pid: number,
  syscalls: string[],
  durationSec: number,
): Promise<{ events: SyscallEvent[]; warnings: string[]; script: string }> {
  const script = buildBpftraceScript(pid, syscalls, durationSec);

  return new Promise((resolve, reject) => {
    // Dynamic import to avoid loading child_process where not needed
    import('node:child_process')
      .then(({ spawn }) => {
        const child = spawn('bpftrace', ['-e', script], {
          stdio: ['ignore', 'pipe', 'pipe'],
          env: { ...process.env },
        });

        const stdoutLines: string[] = [];
        const warnings: string[] = [];
        let stderr = '';
        let settled = false;

        const timer = setTimeout(
          () => {
            if (settled) return;
            settled = true;
            try {
              child.kill('SIGTERM');
            } catch {
              /* ignore */
            }
            // If we got some output, return what we have; otherwise timeout is an error
            if (stdoutLines.length > 0) {
              const { events, warnings: parseWarns } = parseBpftraceJsonl(
                stdoutLines,
                pid,
                syscalls,
              );
              resolve({ events, warnings: [...warnings, ...parseWarns], script });
            } else {
              reject(new Error(`bpftrace timed out after ${durationSec + 5}s with no output`));
            }
          },
          (durationSec + 5) * 1000,
        );

        child.stdout?.on('data', (chunk: Buffer) => {
          const text = chunk.toString();
          const lines = text.split('\n');
          // Keep incomplete last line in buffer (handled by passing full split array)
          for (const line of lines) {
            stdoutLines.push(line);
          }
        });

        child.stderr?.on('data', (chunk: Buffer) => {
          stderr += chunk.toString();
          const lines = stderr.split('\n');
          // Keep the incomplete last entry
          const extra = lines.pop() ?? '';
          for (const line of lines) {
            if (line.trim()) warnings.push(line.trim());
          }
          stderr = extra;
        });

        child.on('error', (err: Error) => {
          if (settled) return;
          settled = true;
          clearTimeout(timer);
          reject(new Error(`bpftrace spawn failed: ${err.message}. Is bpftrace installed?`));
        });

        child.on('close', (code) => {
          if (settled) return;
          settled = true;
          clearTimeout(timer);
          // Flush remaining stderr
          if (stderr.trim()) warnings.push(stderr.trim());

          if (code !== 0 && stdoutLines.length === 0) {
            reject(new Error(`bpftrace exited with code ${code}: ${warnings.join('; ')}`));
            return;
          }

          const {
            events,
            warnings: parseWarns,
            enterCount,
            exitCount,
          } = parseBpftraceJsonl(stdoutLines, pid, syscalls);
          if (enterCount > 0 && exitCount === 0) {
            warnings.push(
              `No exit tracepoints captured. Ensure kernel supports sys_exit tracepoints.`,
            );
          }

          resolve({ events, warnings: [...warnings, ...parseWarns], script });
        });
      })
      .catch(reject);
  });
}

/**
 * Generate simulated events for testing/demo purposes.
 */
function generateSimulatedEvents(
  pid: number,
  syscalls: string[],
  durationSec: number,
): SyscallEvent[] {
  const events: SyscallEvent[] = [];
  const eventCount = Math.max(5, Math.min(syscalls.length * 3, Math.floor(durationSec * 4)));
  const stepMs = (durationSec * 1000) / eventCount;

  for (let i = 0; i < eventCount; i++) {
    const syscallIdx = i % syscalls.length;
    const syscall = syscalls[syscallIdx]!;
    const jitter = i > 0 ? (Math.random() - 0.5) * stepMs * 0.6 : 0;
    const timestamp = i * stepMs + jitter;

    events.push({
      timestamp: Math.max(0, Math.round(timestamp * 100) / 100),
      pid: pid || 1234,
      syscall,
      args: buildSimulatedArgs(syscall, i),
      returnValue: i % 4 === 0 ? -1 : (i + 1) * 64,
      duration: Math.round(Math.random() * 200) / 100,
    });
  }
  return events;
}

function buildSimulatedArgs(syscall: string, i: number): string[] {
  switch (syscall) {
    case 'read':
    case 'write':
      return [`fd=${(i % 7) + 3}`, `count=${(i + 1) * 128}`];
    case 'openat':
      return [
        `pathname=/tmp/jshook_${i}.log`,
        `flags=${i % 2 === 0 ? 'O_RDONLY' : 'O_RDWR'}`,
        `mode=0644`,
      ];
    case 'close':
      return [`fd=${(i % 7) + 3}`];
    case 'connect':
      return [`fd=${(i % 5) + 10}`, `addr=127.0.0.1:${8080 + i}`];
    case 'sendto':
    case 'recvfrom':
      return [`fd=${(i % 5) + 10}`, `count=${(i + 1) * 256}`];
    case 'mmap':
      return [`addr=0x0`, `length=${(i + 1) * 4096}`, `prot=${i % 2 === 0 ? 3 : 7}`, `flags=34`];
    case 'mprotect':
      return [`addr=0x7f000000`, `length=${(i + 1) * 4096}`, `prot=${i % 2 === 0 ? 1 : 7}`];
    case 'clone':
      return [`flags=0x3d0f00`];
    case 'execve':
      return [`filename=/usr/bin/sleep`];
    case 'ioctl':
      return [`fd=${(i % 7) + 3}`, `request=0x${(0x5400 + i).toString(16)}`];
    default:
      return [`arg0=0x${(100 + i).toString(16)}`];
  }
}

// ── Main Handler ───────────────────────────────────────────────────────────────

export async function handleSyscallEbpfAttach(
  args: Record<string, unknown>,
): Promise<EbpfAttachResult> {
  // Parse pid — fail-closed: if pid key exists but is not a valid number, reject
  let pid: number | undefined;
  if (args['pid'] !== undefined && args['pid'] !== null) {
    pid = argNumber(args, 'pid');
    if (pid === undefined || !Number.isInteger(pid) || pid < 0) {
      return {
        success: false,
        error: 'pid must be a non-negative integer (0 for all processes)',
        pid: 0,
        durationSec: 0,
        syscallsTraced: [],
        eventCount: 0,
        mode: 'script',
        liveCapable: false,
        bpftraceAvailable: false,
      };
    }
  }
  const effectivePid = pid ?? 0;

  // Parse syscalls
  const rawSyscalls = argStringArray(args, 'syscalls');
  // If syscalls key was explicitly provided but we got nothing → invalid input
  if (args['syscalls'] !== undefined && rawSyscalls.length === 0) {
    return {
      success: false,
      error: 'syscalls must be an array of valid syscall name strings',
      pid: effectivePid,
      durationSec: 0,
      syscallsTraced: [],
      eventCount: 0,
      mode: 'script',
      liveCapable: false,
      bpftraceAvailable: false,
    };
  }
  const effectiveSyscalls =
    rawSyscalls.length > 0
      ? [...new Set(rawSyscalls.map((s) => s.trim().toLowerCase()).filter(Boolean))]
      : [...DEFAULT_SYSCALLS];

  // Validate syscall names
  const invalid = effectiveSyscalls.filter((s) => !isValidSyscallName(s));
  if (invalid.length > 0) {
    return {
      success: false,
      error: `Invalid syscall names (must be lowercase alphanumeric with underscores): ${invalid.join(', ')}`,
      pid: effectivePid,
      durationSec: 0,
      syscallsTraced: effectiveSyscalls,
      eventCount: 0,
      mode: 'script',
      liveCapable: false,
      bpftraceAvailable: false,
    };
  }

  // Parse durationSec
  let durationSec = argNumber(args, 'durationSec') ?? DEFAULT_TRACE_DURATION_SEC;
  if (!Number.isFinite(durationSec)) durationSec = DEFAULT_TRACE_DURATION_SEC;
  if (durationSec < TRACE_DURATION_MIN_SEC || durationSec > TRACE_DURATION_MAX_SEC) {
    return {
      success: false,
      error: `durationSec must be between ${TRACE_DURATION_MIN_SEC} and ${TRACE_DURATION_MAX_SEC}`,
      pid: effectivePid,
      durationSec,
      syscallsTraced: effectiveSyscalls,
      eventCount: 0,
      mode: 'script',
      liveCapable: false,
      bpftraceAvailable: false,
    };
  }

  // Simulate mode
  const simulate = isArgBool(args, 'simulate');
  if (simulate) {
    const events = generateSimulatedEvents(effectivePid, effectiveSyscalls, durationSec);
    return {
      success: true,
      mode: 'simulated',
      pid: effectivePid,
      durationSec,
      syscallsTraced: effectiveSyscalls,
      events,
      eventCount: events.length,
      liveCapable: process.platform === 'linux',
      bpftraceAvailable: false,
      isSimulated: true,
    };
  }

  // Probe bpftrace availability
  const probe = await probeBpftrace();

  if (probe.available && probe.liveCapable) {
    // Attempt live capture
    try {
      const { events, warnings: captureWarnings } = await captureLiveBpftrace(
        effectivePid,
        effectiveSyscalls,
        durationSec,
      );
      return {
        success: true,
        mode: 'live',
        pid: effectivePid,
        durationSec,
        syscallsTraced: effectiveSyscalls,
        events,
        eventCount: events.length,
        liveCapable: true,
        bpftraceAvailable: true,
        // Include warnings from capture in the script field as a note
        ...(captureWarnings.length > 0
          ? { script: `# Capture warnings:\n# ${captureWarnings.join('\n# ')}` }
          : {}),
      };
    } catch (err) {
      // Live capture failed — fall through to script fallback
      return {
        success: false,
        error: `Live eBPF attach failed: ${err instanceof Error ? err.message : String(err)}`,
        mode: 'script',
        pid: effectivePid,
        durationSec,
        syscallsTraced: effectiveSyscalls,
        eventCount: 0,
        liveCapable: true,
        bpftraceAvailable: probe.available,
      };
    }
  }

  // Script fallback — return the generated script for manual execution
  const script = buildBpftraceScript(effectivePid, effectiveSyscalls, durationSec);
  return {
    success: true,
    mode: 'script',
    pid: effectivePid,
    durationSec,
    syscallsTraced: effectiveSyscalls,
    eventCount: 0,
    script,
    usage: `bpftrace -e '${script.replace(/'/g, "'\\''")}'`,
    liveCapable: probe.liveCapable,
    bpftraceAvailable: probe.available,
  };
}
