import type { ToolRegistration } from '../../registry/types.js';
import { toolLookup } from '../../registry/types.js';
import { browserTools, advancedBrowserToolDefinitions } from './definitions.js';

const t = toolLookup([...browserTools, ...advancedBrowserToolDefinitions]);

export const browserRegistrations: readonly ToolRegistration[] = [
  { tool: t('get_detailed_data'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleGetDetailedData(a) },
  { tool: t('browser_attach'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleBrowserAttach(a) },
  { tool: t('browser_list_tabs'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleBrowserListTabs(a) },
  { tool: t('browser_select_tab'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleBrowserSelectTab(a) },
  { tool: t('browser_launch'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleBrowserLaunch(a) },
  { tool: t('browser_close'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleBrowserClose(a) },
  { tool: t('browser_status'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleBrowserStatus(a) },
  { tool: t('page_navigate'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handlePageNavigate(a) },
  { tool: t('page_reload'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handlePageReload(a) },
  { tool: t('page_back'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handlePageBack(a) },
  { tool: t('page_forward'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handlePageForward(a) },
  { tool: t('dom_query_selector'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleDOMQuerySelector(a) },
  { tool: t('dom_query_all'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleDOMQueryAll(a) },
  { tool: t('dom_get_structure'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleDOMGetStructure(a) },
  { tool: t('dom_find_clickable'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleDOMFindClickable(a) },
  { tool: t('page_click'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handlePageClick(a) },
  { tool: t('page_type'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handlePageType(a) },
  { tool: t('page_select'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handlePageSelect(a) },
  { tool: t('page_hover'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handlePageHover(a) },
  { tool: t('page_scroll'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handlePageScroll(a) },
  { tool: t('page_wait_for_selector'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handlePageWaitForSelector(a) },
  { tool: t('page_evaluate'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handlePageEvaluate(a) },
  { tool: t('page_screenshot'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handlePageScreenshot(a) },
  { tool: t('get_all_scripts'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleGetAllScripts(a) },
  { tool: t('get_script_source'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleGetScriptSource(a) },
  { tool: t('console_enable'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleConsoleEnable(a) },
  { tool: t('console_get_logs'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleConsoleGetLogs(a) },
  { tool: t('console_execute'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleConsoleExecute(a) },
  { tool: t('dom_get_computed_style'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleDOMGetComputedStyle(a) },
  { tool: t('dom_find_by_text'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleDOMFindByText(a) },
  { tool: t('dom_get_xpath'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleDOMGetXPath(a) },
  { tool: t('dom_is_in_viewport'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleDOMIsInViewport(a) },
  { tool: t('page_get_performance'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handlePageGetPerformance(a) },
  { tool: t('page_inject_script'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handlePageInjectScript(a) },
  { tool: t('page_set_cookies'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handlePageSetCookies(a) },
  { tool: t('page_get_cookies'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handlePageGetCookies(a) },
  { tool: t('page_clear_cookies'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handlePageClearCookies(a) },
  { tool: t('page_set_viewport'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handlePageSetViewport(a) },
  { tool: t('page_emulate_device'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handlePageEmulateDevice(a) },
  { tool: t('page_get_local_storage'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handlePageGetLocalStorage(a) },
  { tool: t('page_set_local_storage'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handlePageSetLocalStorage(a) },
  { tool: t('page_press_key'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handlePagePressKey(a) },
  { tool: t('page_get_all_links'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handlePageGetAllLinks(a) },
  { tool: t('captcha_detect'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleCaptchaDetect(a) },
  { tool: t('captcha_wait'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleCaptchaWait(a) },
  { tool: t('captcha_config'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleCaptchaConfig(a) },
  { tool: t('stealth_inject'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleStealthInject(a) },
  { tool: t('stealth_set_user_agent'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleStealthSetUserAgent(a) },
  { tool: t('camoufox_server_launch'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleCamoufoxServerLaunch(a) },
  { tool: t('camoufox_server_close'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleCamoufoxServerClose(a) },
  { tool: t('camoufox_server_status'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleCamoufoxServerStatus(a) },
  { tool: t('framework_state_extract'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleFrameworkStateExtract(a) },
  { tool: t('indexeddb_dump'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleIndexedDBDump(a) },
  { tool: t('js_heap_search'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleJSHeapSearch(a) },
  { tool: t('tab_workflow'), domain: 'browser', bind: (d) => (a) => d.browserHandlers.handleTabWorkflow(a) },
];
