#!/usr/bin/env node
/**
 * Interactive env-tuning helper for jshookmcp.
 *
 * Reads all env-tunable constants from src/constants.ts, lets users
 * pick a preset or tweak individual values, and writes a .env file.
 *
 * Usage:
 *   node scripts/tune-env.mjs                # interactive menu
 *   node scripts/tune-env.mjs --preset lean  # apply preset directly
 *   node scripts/tune-env.mjs --dump         # print current effective values
 *   node scripts/tune-env.mjs --diff         # show non-default overrides in .env
 */
import { promises as fs } from 'fs';
import path from 'path';
import { createInterface } from 'readline';

const ROOT = path.resolve(import.meta.dirname, '..');
const CONSTANTS_PATH = path.join(ROOT, 'src/constants.ts');
const ENV_PATH = path.join(ROOT, '.env');

// ── Parse constants.ts ──

async function parseConstants() {
  const source = await fs.readFile(CONSTANTS_PATH, 'utf-8');
  const entries = [];
  // Match: export const NAME = type('ENV_KEY', default)
  const re =
    /export\s+const\s+([A-Z_][A-Z0-9_]*)\s*=\s*(int|float|bool|str|csv|list)\(\s*['"]([^'"]+)['"]\s*,\s*([^)]+)\)/g;
  let m;
  while ((m = re.exec(source)) !== null) {
    const [, constName, type, envKey, rawDefault] = m;
    entries.push({
      const: constName,
      type,
      envKey,
      default: rawDefault.trim().replace(/_/g, ''),
    });
  }
  return entries;
}

// ── Read existing .env ──

async function readEnv() {
  try {
    const content = await fs.readFile(ENV_PATH, 'utf-8');
    const map = {};
    for (const line of content.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eq = trimmed.indexOf('=');
      if (eq < 0) continue;
      map[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim();
    }
    return map;
  } catch {
    return {};
  }
}

// ── Write .env ──

async function writeEnv(overrides) {
  const lines = [
    '# Auto-generated by scripts/tune-env.mjs',
    `# Generated: ${new Date().toISOString()}`,
    '#',
    '# Only non-default values are written here.',
    '# Delete a line to revert to the built-in default.',
    '',
  ];
  const keys = Object.keys(overrides).toSorted();
  for (const key of keys) {
    lines.push(`${key}=${overrides[key]}`);
  }
  lines.push('');
  await fs.writeFile(ENV_PATH, lines.join('\n'), 'utf-8');
}

// ── Presets ──

const PRESETS = {
  lean: {
    description: 'Minimal memory footprint. Disables vector search, reduces caches, shorter TTLs.',
    values: {
      MCP_TOOL_PROFILE: 'search',
      SEARCH_VECTOR_ENABLED: 'false',
      SEARCH_QUERY_CACHE_CAPACITY: '100',
      ACTIVATION_TTL_MINUTES: '10',
      AUTOPRUNE_AUTO_INACTIVITY_MS: '300000',
      AUTOPRUNE_MANUAL_INACTIVITY_MS: '600000',
      SANDBOX_MEMORY_LIMIT_MB: '64',
      TRANSFORM_CRYPTO_POOL_MAX_WORKERS: '2',
      PREDICTIVE_MAX_HISTORY: '50',
      ACTIVATION_EVENT_HISTORY_MAX: '50',
      TOKEN_BUDGET_MAX_TOKENS: '100000',
      MCP_COMPACT_SCHEMA: 'true',
    },
  },
  balanced: {
    description:
      'Good balance of features and memory. Workflow profile, vector search on, moderate caches.',
    values: {
      MCP_TOOL_PROFILE: 'workflow',
      SEARCH_VECTOR_ENABLED: 'true',
      SEARCH_QUERY_CACHE_CAPACITY: '500',
      ACTIVATION_TTL_MINUTES: '30',
      SANDBOX_MEMORY_LIMIT_MB: '128',
      TRANSFORM_CRYPTO_POOL_MAX_WORKERS: '4',
    },
  },
  full: {
    description: 'All tools loaded at startup. Maximum capability, highest memory.',
    values: {
      MCP_TOOL_PROFILE: 'full',
      SEARCH_VECTOR_ENABLED: 'true',
      SEARCH_QUERY_CACHE_CAPACITY: '1000',
      ACTIVATION_TTL_MINUTES: '0',
    },
  },
  ci: {
    description: 'CI/testing preset. Fast startup, no optional features, strict error handling.',
    values: {
      MCP_TOOL_PROFILE: 'search',
      SEARCH_VECTOR_ENABLED: 'false',
      DISCOVERY_STRICT: 'true',
      SANDBOX_EXEC_TIMEOUT_MS: '3000',
      SANDBOX_MEMORY_LIMIT_MB: '64',
      TRANSFORM_CRYPTO_POOL_MAX_WORKERS: '1',
      ACTIVATION_TTL_MINUTES: '5',
    },
  },
};

// ── CLI ──

const args = process.argv.slice(2);

async function main() {
  const entries = await parseConstants();
  const currentEnv = await readEnv();

  if (args.includes('--dump')) {
    console.log(`\n  ${entries.length} env-tunable constants:\n`);
    const grouped = {};
    for (const e of entries) {
      const prefix = e.envKey.split('_').slice(0, 2).join('_');
      (grouped[prefix] ??= []).push(e);
    }
    for (const [prefix, group] of Object.entries(grouped)) {
      console.log(`  ── ${prefix} ──`);
      for (const e of group) {
        const override = currentEnv[e.envKey];
        const marker = override !== undefined ? ` ← .env: ${override}` : '';
        console.log(`    ${e.envKey.padEnd(45)} ${e.type.padEnd(5)} default=${e.default}${marker}`);
      }
    }
    console.log(
      `\n  Total: ${entries.length} constants | ${Object.keys(currentEnv).length} overrides in .env\n`,
    );
    return;
  }

  if (args.includes('--diff')) {
    const overrideKeys = Object.keys(currentEnv);
    if (overrideKeys.length === 0) {
      console.log('\n  No .env overrides. All values are at defaults.\n');
      return;
    }
    console.log(`\n  .env overrides (${overrideKeys.length}):\n`);
    for (const key of overrideKeys.toSorted()) {
      const entry = entries.find((e) => e.envKey === key);
      const defaultVal = entry ? entry.default : '(unknown)';
      console.log(`    ${key.padEnd(45)} ${currentEnv[key].padEnd(15)} (default: ${defaultVal})`);
    }
    console.log();
    return;
  }

  if (args.includes('--preset')) {
    const presetName = args[args.indexOf('--preset') + 1];
    const preset = PRESETS[presetName];
    if (!preset) {
      console.error(
        `Unknown preset "${presetName}". Available: ${Object.keys(PRESETS).join(', ')}`,
      );
      process.exit(1);
    }
    await writeEnv(preset.values);
    console.log(`\n  Applied preset "${presetName}": ${preset.description}`);
    console.log(`  Wrote ${Object.keys(preset.values).length} values to .env\n`);
    for (const [k, v] of Object.entries(preset.values)) {
      console.log(`    ${k.padEnd(45)} = ${v}`);
    }
    console.log();
    return;
  }

  // Interactive menu
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const ask = (q) => new Promise((r) => rl.question(q, r));

  console.log('\n  jshookmcp env tuner\n');
  console.log('  Presets:');
  for (const [name, preset] of Object.entries(PRESETS)) {
    console.log(`    ${name.padEnd(12)} ${preset.description}`);
  }
  console.log();

  const choice = await ask('  Enter preset name (lean/balanced/full/ci) or "custom" for manual: ');

  if (PRESETS[choice.trim()]) {
    const preset = PRESETS[choice.trim()];
    await writeEnv(preset.values);
    console.log(`\n  Applied "${choice.trim()}" preset → .env\n`);
  } else if (choice.trim() === 'custom') {
    console.log('\n  Key env variables for tuning:\n');
    const tunable = [
      'MCP_TOOL_PROFILE',
      'SEARCH_VECTOR_ENABLED',
      'SEARCH_QUERY_CACHE_CAPACITY',
      'ACTIVATION_TTL_MINUTES',
      'SANDBOX_MEMORY_LIMIT_MB',
      'SANDBOX_EXEC_TIMEOUT_MS',
      'TRANSFORM_CRYPTO_POOL_MAX_WORKERS',
      'TOKEN_BUDGET_MAX_TOKENS',
      'MCP_COMPACT_SCHEMA',
    ];
    const overrides = { ...currentEnv };
    for (const key of tunable) {
      const entry = entries.find((e) => e.envKey === key);
      const current = currentEnv[key] ?? entry?.default ?? '(none)';
      const val = await ask(`    ${key} [${current}]: `);
      if (val.trim()) {
        overrides[key] = val.trim();
      }
    }
    await writeEnv(overrides);
    console.log(`\n  Wrote ${Object.keys(overrides).length} values to .env\n`);
  } else {
    console.log('  No changes made.');
  }

  rl.close();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
