/**
 * TLS Key Log Extractor tests.
 */

import { describe, expect, it } from 'vitest';
import {
  enableKeyLog,
  disableKeyLog,
  getKeyLogFilePath,
  parseKeyLog,
  decryptPayload,
  summarizeKeyLog,
  lookupSecret,
} from '@modules/boringssl-inspector/TLSKeyLogExtractor';

describe('TLSKeyLogExtractor', () => {
  describe('enableKeyLog', () => {
    it('sets SSLKEYLOGFILE env var', () => {
      const path = enableKeyLog('/tmp/test-sslkeylog.log');
      expect(process.env.SSLKEYLOGFILE).toBe('/tmp/test-sslkeylog.log');
      expect(path).toBe('/tmp/test-sslkeylog.log');
      disableKeyLog();
    });

    it('uses default path when not specified', () => {
      const path = enableKeyLog();
      expect(path).toBe('/tmp/sslkeylog.log');
      expect(process.env.SSLKEYLOGFILE).toBe('/tmp/sslkeylog.log');
      disableKeyLog();
    });
  });

  describe('getKeyLogFilePath', () => {
    it('returns null when not configured', () => {
      disableKeyLog();
      expect(getKeyLogFilePath()).toBeNull();
    });

    it('returns path after enabling', () => {
      enableKeyLog('/tmp/custom.log');
      expect(getKeyLogFilePath()).toBe('/tmp/custom.log');
      disableKeyLog();
    });
  });

  describe('disableKeyLog', () => {
    it('removes SSLKEYLOGFILE env var', () => {
      enableKeyLog('/tmp/test.log');
      disableKeyLog();
      expect(process.env.SSLKEYLOGFILE).toBeUndefined();
      expect(getKeyLogFilePath()).toBeNull();
    });
  });

  describe('parseKeyLog', () => {
    it('parses CLIENT_RANDOM entries', () => {
      const content = `# SSL/TLS secrets log file, generated by jshookmcp
CLIENT_RANDOM abc123def456 secret789abc`;
      const entries = parseKeyLog(content);

      expect(entries).toHaveLength(1);
      expect(entries[0]?.label).toBe('CLIENT_RANDOM');
      expect(entries[0]?.clientRandom).toBe('abc123def456');
      expect(entries[0]?.secret).toBe('secret789abc');
    });

    it('parses multiple entries with different labels', () => {
      const content = `CLIENT_RANDOM abcd 1111
CLIENT_HANDSHAKE_TRAFFIC_SECRET abcd 2222
SERVER_HANDSHAKE_TRAFFIC_SECRET abcd 3332
CLIENT_TRAFFIC_SECRET_0 abcd 4444
SERVER_TRAFFIC_SECRET_0 abcd 5555
EXPORTER_SECRET abcd 6666`;
      const entries = parseKeyLog(content);

      expect(entries).toHaveLength(6);
      expect(entries.map((e) => e.label)).toEqual([
        'CLIENT_RANDOM',
        'CLIENT_HANDSHAKE_TRAFFIC_SECRET',
        'SERVER_HANDSHAKE_TRAFFIC_SECRET',
        'CLIENT_TRAFFIC_SECRET_0',
        'SERVER_TRAFFIC_SECRET_0',
        'EXPORTER_SECRET',
      ]);
    });

    it('skips comments and empty lines', () => {
      const content = `# Header comment

# Another comment
CLIENT_RANDOM abcd 1111

`;
      const entries = parseKeyLog(content);
      expect(entries).toHaveLength(1);
    });

    it('skips malformed lines', () => {
      const content = `CLIENT_RANDOM abcd 1111
ONLY_TWO_PARTS
CLIENT_RANDOM efgh 2222`;
      const entries = parseKeyLog(content);
      expect(entries).toHaveLength(2);
    });

    it('handles empty content', () => {
      const entries = parseKeyLog('');
      expect(entries).toHaveLength(0);
    });
  });

  describe('summarizeKeyLog', () => {
    it('returns summary statistics', () => {
      const entries = parseKeyLog(`CLIENT_RANDOM abcd 1111
CLIENT_HANDSHAKE_TRAFFIC_SECRET abcd 2222
SERVER_TRAFFIC_SECRET_0 efgh 3333`);
      const summary = summarizeKeyLog(entries);

      expect(summary.totalEntries).toBe(3);
      expect(summary.uniqueClients).toBe(2);
      expect(summary.hasClientRandom).toBe(true);
      expect(summary.hasTrafficSecrets).toBe(true);
      expect(summary.labels).toContain('CLIENT_RANDOM');
    });

    it('handles empty entries', () => {
      const summary = summarizeKeyLog([]);
      expect(summary.totalEntries).toBe(0);
      expect(summary.uniqueClients).toBe(0);
      expect(summary.hasClientRandom).toBe(false);
      expect(summary.hasTrafficSecrets).toBe(false);
    });
  });

  describe('lookupSecret', () => {
    it('finds secret by client random', () => {
      const entries = parseKeyLog(`CLIENT_RANDOM abcd secret1234
CLIENT_RANDOM efgh secret5678`);
      const secret = lookupSecret(entries, 'abcd');
      expect(secret).toBe('secret1234');
    });

    it('finds secret by client random and label', () => {
      const entries = parseKeyLog(`CLIENT_RANDOM abcd secret1
CLIENT_HANDSHAKE_TRAFFIC_SECRET abcd secret2`);
      const secret = lookupSecret(entries, 'abcd', 'CLIENT_HANDSHAKE_TRAFFIC_SECRET');
      expect(secret).toBe('secret2');
    });

    it('returns null for unknown client random', () => {
      const entries = parseKeyLog(`CLIENT_RANDOM abcd secret1`);
      const secret = lookupSecret(entries, 'zzzz');
      expect(secret).toBeNull();
    });

    it('is case-insensitive for client random', () => {
      const entries = parseKeyLog(`CLIENT_RANDOM ABCD secret1`);
      const secret = lookupSecret(entries, 'abcd');
      expect(secret).toBe('secret1');
    });
  });

  describe('decryptPayload', () => {
    it('returns decrypted text for valid input', async () => {
      const crypto = await import('node:crypto');
      const key = crypto.randomBytes(32); // AES-256
      const nonce = crypto.randomBytes(12); // GCM nonce
      const plaintext = 'Hello, TLS!';
      const cipher = crypto.createCipheriv('aes-256-gcm', key, nonce);
      let encrypted = cipher.update(Buffer.from(plaintext, 'utf-8'));
      encrypted = Buffer.concat([encrypted, cipher.final()]);
      const authTag = cipher.getAuthTag();

      const result = decryptPayload(
        encrypted.toString('hex'),
        key.toString('hex'),
        nonce.toString('hex'),
        'aes-256-gcm',
        authTag.toString('hex'),
      );

      expect(result).toBe(plaintext);
    });

    it('returns replacement characters for non-UTF-8 decrypted data', async () => {
      const crypto = await import('node:crypto');
      const key = crypto.randomBytes(16); // AES-128
      const nonce = crypto.randomBytes(12);
      // Encrypt binary data that won't be valid UTF-8
      const binaryData = Buffer.from([0x80, 0x81, 0x82, 0x83]);
      const cipher = crypto.createCipheriv('aes-128-gcm', key, nonce);
      let encrypted = cipher.update(binaryData);
      encrypted = Buffer.concat([encrypted, cipher.final()]);
      const authTag = cipher.getAuthTag();

      const result = decryptPayload(
        encrypted.toString('hex'),
        key.toString('hex'),
        nonce.toString('hex'),
        'aes-128-gcm',
        authTag.toString('hex'),
      );

      // Should return something (replacement chars or decoded text)
      expect(typeof result).toBe('string');
      expect(result.length).toBeGreaterThan(0);
    });

    it('returns failure message for invalid key', () => {
      const result = decryptPayload(
        'aabbccdd',
        '0000000000000000000000000000000000000000000000000000000000000000',
        '000000000000000000000000',
      );
      expect(result).toContain('DECRYPTION_FAILED');
    });

    it('supports chacha20-poly1305', () => {
      const result = decryptPayload(
        'aabbccdd',
        '0000000000000000000000000000000000000000000000000000000000000000',
        '000000000000000000000000',
        'chacha20-poly1305',
      );
      // Should attempt decryption (may fail with wrong data, but not fail setup)
      expect(typeof result).toBe('string');
    });

    it('handles hex input with whitespace', () => {
      const result = decryptPayload(
        'aa bb cc dd',
        '00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00',
        '00 00 00 00 00 00 00 00 00 00 00 00',
      );
      expect(typeof result).toBe('string');
    });
  });
});
