export const EXCLUDE_SELECTORS = [
  '[class*="video"]',
  '[class*="player"]',
  '[id*="video"]',
  '[id*="player"]',
  '[class*="swiper"]',
  '[class*="carousel"]',
  '[class*="banner"]',
  '[class*="gallery"]',
  '[class*="douyin"]',
  '[class*="tiktok"]',
  '[class*="scroll"]',
  '[class*="scrollbar"]',
  '[class*="progress"]',
  '[class*="range"]',
  '[class*="volume"]',
] as const;

export const CAPTCHA_SELECTORS = {
  slider: [
    '.captcha-slider',
    '.verify-slider',
    '#captcha-slider',
    '.slide-verify',
    '[class*="captcha"][class*="slider"]',
    '[class*="verify"][class*="slider"]',
    '[id*="captcha"][id*="slider"]',
    '[id*="verify"][id*="slider"]',
    '[aria-label*="slider" i]',
  ],
  image: [
    '[class*="captcha-image"]',
    '[id*="captcha-image"]',
    '.verify-img',
    '.captcha-img',
    'img[src*="captcha"]',
    'img[alt*=""]',
    'img[alt*="captcha"]',
  ],
  widget: [
    'iframe[src*="captcha" i]',
    'iframe[src*="challenge" i]',
    'iframe[title*="captcha" i]',
    'iframe[title*="verification" i]',
    '[data-sitekey]',
    '[class*="captcha"][class*="widget"]',
    '[class*="challenge"][class*="widget"]',
    '[class*="human"][class*="check"]',
  ],
  browserCheck: [
    '#challenge-form',
    '[id*="challenge-form"]',
    '[class*="browser-check"]',
    '[class*="security-check"]',
    '[class*="challenge-page"]',
    '[class*="challenge-container"]',
  ],
  generic: [
    '[class*="captcha"]',
    '[id*="captcha"]',
    '[class*="verify"]',
    '[id*="verify"]',
    '[class*="challenge"]',
    '[id*="challenge"]',
    'iframe[src*="captcha"]',
    'iframe[src*="verify"]',
  ],
} as const;
